<?php
$mensagensUtilizadas=(int)($consumo['CMS_Mensagens']??0); $limiteMensagens=(int)($cliente['PLA_LimiteMensagens']??0);
$percentualUso=$limiteMensagens>0?min(100,round(($mensagensUtilizadas/$limiteMensagens)*100)):0;
$corBarra=$percentualUso>=100?'danger':($percentualUso>=80?'warning':'success');
$temExcedente=!empty($excedente)&&(int)($excedente['EXC_Mensagens']??0)>0;
$qualidade=['GREEN'=>'Boa','YELLOW'=>'Média','RED'=>'Baixa'][$metaConta['MTA_QualityRating']??'']??'Não disponível';
$avisoMeta=$metaConta?avisoMetaDashboard($metaConta):null;
?>
<style>
.cliente-dashboard .small-box{border-radius:.45rem;box-shadow:0 2px 8px rgba(0,0,0,.08)}.cliente-dashboard .resumo-card{border-radius:.5rem;box-shadow:0 2px 8px rgba(0,0,0,.06);height:100%}
.cliente-dashboard .resumo-card .card-header{display:flex;align-items:center;justify-content:space-between}.cliente-dashboard .plano-nome{font-size:1.45rem;font-weight:700}.cliente-dashboard .plano-valor{font-size:1.25rem;font-weight:700;color:#28a745}
.cliente-dashboard .mini-info{background:#f7f8fa;border-radius:.4rem;padding:.7rem;height:100%}.cliente-dashboard .mini-info strong{display:block;font-size:1.1rem}.cliente-dashboard .uso-box{background:#f7f9fc;border-radius:.4rem;padding:.85rem}
.cliente-dashboard .extra-box{background:#fff8e8;border:1px solid #ffe2a6;border-radius:.4rem;padding:.75rem}.cliente-dashboard .acoes-grid{display:grid;grid-template-columns:1fr 1fr;gap:.7rem}
.cliente-dashboard .acao{display:block;text-align:center;padding:1rem .6rem;border:1px solid #e1e5ea;border-radius:.45rem;background:#f8f9fa;color:#344054}.cliente-dashboard .acao:hover{text-decoration:none;background:#eef5ff}.cliente-dashboard .acao i{display:block;font-size:1.35rem;margin-bottom:.35rem}
@media(max-width:767px){.cliente-dashboard .acoes-grid{grid-template-columns:1fr}.cliente-dashboard .resumo-card{height:auto}}
</style>
<div class="cliente-dashboard">
<div class="d-flex flex-wrap justify-content-between align-items-start mb-3">
 <div><h4 class="mb-0">Olá, <?= htmlspecialchars($usuario['nome'] ?? ''); ?>!</h4><small class="text-muted">Aqui está um resumo da sua conta no Disparador.</small></div>
 <?php if($ultimoAcessoCliente){ ?><small class="text-muted mt-1"><i class="far fa-clock mr-1"></i>Último acesso: <?= date('d/m/Y \à\s H:i', strtotime($ultimoAcessoCliente)); ?></small><?php } ?>
</div>
<div class="row">
<?php foreach([
 ['bg-info','fas fa-comments',$conversas,'Conversas','conversa','Abrir conversas'],['bg-danger','fas fa-envelope',$naoLidas,'Não lidas','conversa','Ver pendências'],
 ['bg-success','fas fa-address-book',$contatos,'Contatos','listaContato','Ver listas'],['bg-warning','fas fa-bullhorn',$campanhas,'Campanhas','campanha','Ver campanhas']
] as $box){ ?><div class="col-lg-3 col-6"><div class="small-box <?= $box[0]; ?>"><div class="inner"><h3><?= number_format($box[2],0,',','.'); ?></h3><p><?= $box[3]; ?></p></div><div class="icon"><i class="<?= $box[1]; ?>"></i></div><a href="<?= BASE_URL; ?>/index.php?url=<?= $box[4]; ?>" class="small-box-footer"><?= $box[5]; ?> <i class="fas fa-arrow-circle-right"></i></a></div></div><?php } ?>
</div>
<div class="row mb-3">
<div class="col-xl-4 col-lg-6 mb-3"><div class="card card-outline card-primary resumo-card"><div class="card-header"><h3 class="card-title"><i class="fas fa-crown text-primary mr-2"></i>Seu plano</h3><span class="badge badge-<?= ($cliente['CLI_StatusPagamento']??'')==='pago'?'success':'warning'; ?>"><?= ($cliente['CLI_StatusPagamento']??'')==='pago'?'Ativo':'Pendente'; ?></span></div><div class="card-body">
<?php if(!empty($cliente['PLA_Nome'])){ ?><div class="plano-nome"><?= htmlspecialchars($cliente['PLA_Nome']); ?></div><div class="plano-valor mb-3">R$ <?= number_format((float)$cliente['PLA_Valor'],2,',','.'); ?> / mês</div>
<div class="row mb-3"><div class="col-4"><div class="mini-info"><small class="text-muted">Mensagens</small><strong><?= number_format($limiteMensagens,0,',','.'); ?></strong><small>por mês</small></div></div><div class="col-4"><div class="mini-info"><small class="text-muted">Números</small><strong><?= (int)$cliente['PLA_LimiteNumeros']; ?></strong></div></div><div class="col-4"><div class="mini-info"><small class="text-muted">Usuários</small><strong><?= (int)$cliente['PLA_LimiteUsuarios']; ?></strong></div></div></div>
<div class="uso-box mb-<?= $temExcedente?'2':'0'; ?>"><div class="d-flex justify-content-between"><strong>Uso do plano</strong><strong><?= $percentualUso; ?>%</strong></div><div class="mb-2"><?= number_format(min($mensagensUtilizadas,$limiteMensagens),0,',','.'); ?> de <?= number_format($limiteMensagens,0,',','.'); ?> mensagens</div><div class="progress" style="height:9px"><div class="progress-bar bg-<?= $corBarra; ?>" style="width:<?= $percentualUso; ?>%"></div></div></div>
<?php if($temExcedente){ ?><div class="extra-box"><strong><i class="fas fa-coins text-warning mr-1"></i> Mensagens extras</strong><div><strong><?= number_format((int)$excedente['EXC_Mensagens'],0,',','.'); ?></strong> mensagens · <strong class="text-warning">R$ <?= number_format((float)$excedente['EXC_ValorTotal'],2,',','.'); ?></strong> em excedentes</div></div><?php } ?>
<?php }else{ ?><div class="alert alert-warning mb-0"><?= $clienteEmPreTrialDashboard?'Você está preparando seu período de avaliação.':'Nenhum plano contratado.'; ?></div><?php } ?>
</div></div></div>
<div class="col-xl-4 col-lg-6 mb-3"><div class="card card-outline card-success resumo-card"><div class="card-header"><h3 class="card-title"><i class="fab fa-whatsapp text-success mr-2"></i>Conta Meta</h3><?php if($metaConta){ ?><span class="badge badge-<?= $metaConta['MTA_Status']==='conectado'?'success':'danger'; ?>"><?= $metaConta['MTA_Status']==='conectado'?'Conectada':'Atenção'; ?></span><?php } ?></div><div class="card-body">
<?php if($metaConta){ ?><h5 class="font-weight-bold"><?= htmlspecialchars(($metaConta['MTA_DisplayName'] ?? '') ?: ($metaConta['MTA_Nome'] ?? 'Conta Meta')); ?></h5><p class="mb-1"><strong>Número:</strong> <span id="numeroMetaDashboard"><?= htmlspecialchars(formatarTelefoneDashboard($metaConta['MTA_NumeroTelefone'])); ?></span></p><p class="mb-1"><strong>Qualidade:</strong> <span id="qualidadeMetaDashboard"><?= htmlspecialchars($qualidade); ?></span></p><p class="mb-1"><strong>Limite da Meta:</strong><br><span id="limiteMetaDashboard"><?= htmlspecialchars(\Services\MetaService::formatarLimiteConversasMeta($metaConta['MTA_MessagingLimit']??null)); ?></span></p><p class="mb-2"><strong>Última atualização:</strong> <span id="ultimaMetaDashboard"><?= !empty($metaConta['MTA_UltimaVerificacao'])?date('d/m/Y \à\s H:i',strtotime($metaConta['MTA_UltimaVerificacao'])):'Ainda não atualizada'; ?></span></p>
<div id="avisoMetaDashboard" class="alert alert-warning py-2 <?= $avisoMeta?'':'d-none'; ?>"><?= htmlspecialchars($avisoMeta?:''); ?></div><form id="formAtualizarMetaDashboard" method="post" action="<?= BASE_URL; ?>/index.php?url=configuracao/atualizarStatusMetaAjax"><?= \Core\Csrf::input(); ?><input type="hidden" name="conta_id" value="<?= (int)$metaConta['MTA_ID']; ?>"><button id="btnAtualizarMetaDashboard" type="submit" class="btn btn-outline-success btn-block"><i class="fas fa-sync-alt mr-1"></i> Atualizar dados da Meta</button></form><div id="retornoMetaDashboard" class="small mt-2"></div>
<?php }else{ ?><div class="alert alert-warning mb-0">Nenhuma conta Meta cadastrada.</div><?php } ?></div></div></div>
<div class="col-xl-4 col-lg-12 mb-3"><div class="card card-outline card-info resumo-card"><div class="card-header"><h3 class="card-title"><i class="fas fa-bolt text-info mr-2"></i>Ações rápidas</h3></div><div class="card-body"><div class="acoes-grid">
<a class="acao" href="<?= BASE_URL; ?>/index.php?url=campanha"><i class="fas fa-paper-plane text-primary"></i><strong>Nova campanha</strong><small class="d-block text-muted">Criar e enviar</small></a><a class="acao" href="<?= BASE_URL; ?>/index.php?url=listaContato"><i class="fas fa-users text-success"></i><strong>Gerenciar contatos</strong><small class="d-block text-muted">Listas e importação</small></a><a class="acao" href="<?= BASE_URL; ?>/index.php?url=template"><i class="fas fa-file-alt text-purple"></i><strong>Templates</strong><small class="d-block text-muted">Criar e gerenciar</small></a><a class="acao" href="<?= BASE_URL; ?>/index.php?url=configuracao/meta"><i class="fas fa-cog text-secondary"></i><strong>Configurações</strong><small class="d-block text-muted">Conta Meta</small></a>
</div></div></div></div></div>
<div class="card"><div class="card-header d-flex align-items-center"><h3 class="card-title"><i class="fas fa-bullhorn text-primary mr-2"></i>Últimas campanhas</h3><a href="<?= BASE_URL; ?>/index.php?url=campanha" class="ml-auto">Ver todas as campanhas <i class="fas fa-arrow-right ml-1"></i></a></div><div class="card-body table-responsive p-0"><table class="table table-hover table-striped mb-0"><thead><tr><th>Nome</th><th>Status</th><th>Agendamento</th><th>Contatos</th><th>Enviados</th></tr></thead><tbody>
<?php if(empty($ultimasCampanhas)){ ?><tr><td colspan="5" class="text-center text-muted">Nenhuma campanha encontrada.</td></tr><?php } ?><?php foreach($ultimasCampanhas as $campanha){ ?><tr><td><?= htmlspecialchars($campanha['CAM_Nome']); ?></td><td><span class="badge badge-secondary"><?= htmlspecialchars($campanha['CAM_Status']); ?></span></td><td><?= formatarDataDashboard($campanha['CAM_DataAgendamento']); ?></td><td><?= number_format($campanha['CAM_TotalContatos'],0,',','.'); ?></td><td><?= number_format($campanha['CAM_TotalEnviados'],0,',','.'); ?></td></tr><?php } ?></tbody></table></div></div>
</div>
<?php if($metaConta){ ?><script>
(function(){var form=document.getElementById('formAtualizarMetaDashboard');if(!form)return;form.addEventListener('submit',function(e){e.preventDefault();var btn=document.getElementById('btnAtualizarMetaDashboard'),ret=document.getElementById('retornoMetaDashboard');btn.disabled=true;btn.innerHTML='<i class="fas fa-spinner fa-spin mr-1"></i> Atualizando...';ret.className='small mt-2 text-muted';ret.textContent='Consultando a Meta...';fetch(form.action,{method:'POST',body:new FormData(form),credentials:'same-origin',headers:{'X-Requested-With':'XMLHttpRequest'}}).then(function(r){return r.json().then(function(j){return{ok:r.ok,json:j};});}).then(function(resp){if(!resp.ok||!resp.json.ok)throw new Error(resp.json.mensagem||'Não foi possível atualizar.');var d=resp.json.dados||{};ret.className='small mt-2 text-success';ret.textContent=resp.json.mensagem||'Dados atualizados.';if(d.numero)document.getElementById('numeroMetaDashboard').textContent=d.numero;if(d.messaging_limit_label)document.getElementById('limiteMetaDashboard').textContent=d.messaging_limit_label;if(d.quality_rating){var q={GREEN:'Boa',YELLOW:'Média',RED:'Baixa'};document.getElementById('qualidadeMetaDashboard').textContent=q[d.quality_rating]||d.quality_rating;}if(d.ultima_verificacao){var dt=new Date(d.ultima_verificacao.replace(' ','T'));if(!isNaN(dt.getTime()))document.getElementById('ultimaMetaDashboard').textContent=dt.toLocaleDateString('pt-BR')+' às '+dt.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});}document.getElementById('avisoMetaDashboard').classList.add('d-none');}).catch(function(err){ret.className='small mt-2 text-danger';ret.textContent=err.message;}).finally(function(){btn.disabled=false;btn.innerHTML='<i class="fas fa-sync-alt mr-1"></i> Atualizar dados da Meta';});});})();
</script><?php } ?>