<?php
if(!extension_loaded('pdo_sqlite')){echo "IndicacaoWorkflowTest SKIP: pdo_sqlite indisponível\n";exit(0);}
$root=dirname(__DIR__);spl_autoload_register(function($classe)use($root){$mapa=['Models\\'=>$root.'/app/Models/','Services\\'=>$root.'/app/Services/','Core\\'=>$root.'/app/Core/'];foreach($mapa as $prefixo=>$base){if(strpos($classe,$prefixo)===0){$f=$base.str_replace('\\','/',substr($classe,strlen($prefixo))).'.php';if(is_file($f))require_once$f;return;}}});
use Models\{Cliente,Indicacao,IndicacaoAuditoria,IndicacaoCampanha,IndicacaoCodigo};
use Services\{IndicacaoAuditoriaService,IndicacaoCodigoService,IndicacaoService};
use Services\Indicacao\{CodigoIndicacaoPadraoGenerator,IndicacaoWorkflowService};
function iwAssert($ok,$m){if(!$ok){fwrite(STDERR,"FAIL: $m\n");exit(1);}}
function iwDomain(callable $f,$m){try{$f();iwAssert(false,$m);}catch(DomainException $e){iwAssert(strpos($e->getMessage(),'SQL')===false,$m.' sem SQL bruto');}}
function iwDb(){
 $db=new PDO('sqlite::memory:');$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec("PRAGMA foreign_keys=ON;
 CREATE TABLE clientes(CLI_ID INTEGER PRIMARY KEY,CLI_Nome TEXT);
 CREATE TABLE indicacao_campanhas(ICP_ID INTEGER PRIMARY KEY,ICP_Nome TEXT,ICP_Descricao TEXT,ICP_Percentual REAL,ICP_DataInicio TEXT,ICP_DataFim TEXT,ICP_Ativo TEXT,ICP_Publica TEXT,ICP_RegrasSnapshot TEXT,ICP_CriadoPor_USU_ID INTEGER);
 CREATE TABLE indicacao_codigos(ICD_ID INTEGER PRIMARY KEY,CLI_ID INTEGER,ICP_ID INTEGER,ICD_Codigo TEXT,ICD_CodigoNormalizado TEXT UNIQUE,ICD_Status TEXT,ICD_LiberadoEm TEXT,ICD_SuspensoEm TEXT,ICD_CanceladoEm TEXT,UNIQUE(CLI_ID,ICP_ID));
 CREATE TABLE indicacoes(IND_ID INTEGER PRIMARY KEY AUTOINCREMENT,ICD_ID INTEGER,ICP_ID INTEGER,CLI_Indicador_ID INTEGER,CLI_Indicado_ID INTEGER UNIQUE,IND_PercentualSnapshot REAL,IND_Origem TEXT,IND_Status TEXT,IND_CadastradaEm TEXT,IND_PagamentoConfirmadoEm TEXT,IND_ConfirmacaoAte TEXT,IND_AprovadaEm TEXT,IND_CanceladaEm TEXT,IND_FraudeEm TEXT,IND_InelegivelEm TEXT,IND_Motivo TEXT,UNIQUE(ICD_ID,CLI_Indicado_ID));
 CREATE TABLE indicacao_auditoria(IAU_ID INTEGER PRIMARY KEY AUTOINCREMENT,IAU_Entidade TEXT,IAU_EntidadeID INTEGER,IAU_Acao TEXT,IAU_StatusAnterior TEXT,IAU_StatusNovo TEXT,IAU_Motivo TEXT,USU_ID INTEGER,IAU_Correlacao TEXT,IAU_Dados TEXT,IAU_CriadoEm TEXT DEFAULT CURRENT_TIMESTAMP);");
 $db->exec("INSERT INTO clientes VALUES(1,'Indicador'),(2,'Indicado link'),(3,'Indicado manual'),(4,'Duplicado'),(5,'Status'),(6,'Campanha'),(7,'Rollback'),(8,'Concorrente'),(10,'Dono 10'),(11,'Dono 11'),(12,'Dono 12'),(13,'Dono 13'),(14,'Dono 14'),(15,'Dono 15'),(16,'Dono 16');
 INSERT INTO indicacao_campanhas VALUES(1,'Inicial',NULL,15,'2020-01-01 00:00:00',NULL,'S','S','{}',NULL),(2,'Inativa',NULL,20,'2020-01-01 00:00:00',NULL,'N','S','{}',NULL),(3,'Futura',NULL,25,'2099-01-01 00:00:00',NULL,'S','S','{}',NULL),(4,'Encerrada',NULL,25,'2020-01-01 00:00:00','2020-02-01 00:00:00','S','S','{}',NULL),(5,'Privada',NULL,30,'2020-01-01 00:00:00',NULL,'S','N','{}',NULL);
 INSERT INTO indicacao_codigos VALUES(1,1,1,'ROD-8XJ4P','ROD8XJ4P','ativo',NULL,NULL,NULL),(2,10,1,'NAO-ABCDE','NAOABCDE','nao_liberado',NULL,NULL,NULL),(3,11,1,'SUS-ABCDE','SUSABCDE','suspenso',NULL,NULL,NULL),(4,12,1,'CAN-ABCDE','CANABCDE','cancelado',NULL,NULL,NULL),(5,13,2,'INA-ABCDE','INAABCDE','ativo',NULL,NULL,NULL),(6,14,3,'FUT-ABCDE','FUTABCDE','ativo',NULL,NULL,NULL),(7,15,4,'ENC-ABCDE','ENCABCDE','ativo',NULL,NULL,NULL),(8,16,5,'PRI-ABCDE','PRIABCDE','ativo',NULL,NULL,NULL),(9,99,1,'DON-ABCDE','DONABCDE','ativo',NULL,NULL,NULL);");return$db;
}
function iwServices(PDO$db,$indicacaoModel=null,$audit=null){$aModel=new IndicacaoAuditoria($db);$audit=$audit?:new IndicacaoAuditoriaService($aModel);$cModel=new IndicacaoCampanha($db);$iModel=$indicacaoModel?:new Indicacao($db);$codigoModel=new IndicacaoCodigo($db);$codigoService=new IndicacaoCodigoService($db,$codigoModel,$audit,new CodigoIndicacaoPadraoGenerator());$indicacaoService=new IndicacaoService($db,$iModel,$cModel,$audit);return [new IndicacaoWorkflowService($db,$codigoService,$cModel,$iModel,new Cliente($db),$indicacaoService),$iModel,$aModel];}
$db=iwDb();[$workflow,$indicacoes,$auditoria]=iwServices($db);
$v=$workflow->validarCodigo('  rod-8xj4p  ');iwAssert($v['codigo']['ICD_ID']==1&&$v['campanha']['ICP_ID']==1,'código normalizado e campanha vinculada');
$id=$workflow->registrarIndicacao(2,' rod-8xj4p ','link');$i=$indicacoes->buscar($id);iwAssert($i['IND_Status']==='aguardando_pagamento','trilha cadastrada para aguardando pagamento');iwAssert((int)$i['ICP_ID']===1&&(float)$i['IND_PercentualSnapshot']===15.0&&$i['IND_Origem']==='link','campanha e percentual congelados');
$db->exec("UPDATE indicacao_campanhas SET ICP_Percentual=77,ICP_Ativo='N' WHERE ICP_ID=1");$depois=$indicacoes->buscar($id);iwAssert((float)$depois['IND_PercentualSnapshot']===15.0&&(int)$depois['ICP_ID']===1,'alteração posterior não muda snapshot/campanha');iwAssert($db->query("SELECT ICD_Codigo FROM indicacao_codigos WHERE ICD_ID=1")->fetchColumn()==='ROD-8XJ4P','código permanece congelado');$db->exec("UPDATE indicacao_campanhas SET ICP_Percentual=15,ICP_Ativo='S' WHERE ICP_ID=1");
$idManual=$workflow->registrarIndicacao(3,'ROD8XJ4P','manual');iwAssert($indicacoes->buscar($idManual)['IND_Origem']==='manual','origem manual');
iwDomain(function()use($workflow){$workflow->validarCodigo('inexistente');},'código inexistente');foreach(['NAO-ABCDE','SUS-ABCDE','CAN-ABCDE']as$c)iwDomain(function()use($workflow,$c){$workflow->validarCodigo($c);},'status de código rejeitado');foreach(['INA-ABCDE','FUT-ABCDE','ENC-ABCDE','PRI-ABCDE']as$c)iwDomain(function()use($workflow,$c){$workflow->validarCodigo($c);},'campanha inelegível rejeitada');iwDomain(function()use($workflow){$workflow->validarCodigo('DON-ABCDE');},'indicador inexistente');iwDomain(function()use($workflow){$workflow->registrarIndicacao(404,'ROD-8XJ4P','link');},'indicado inexistente');iwDomain(function()use($workflow){$workflow->registrarIndicacao(1,'ROD-8XJ4P','link');},'autoindicação');try{$workflow->registrarIndicacao(5,'ROD-8XJ4P','outra');iwAssert(false,'origem inválida');}catch(InvalidArgumentException$e){}
iwDomain(function()use($workflow){$workflow->registrarIndicacao(2,'ROD-8XJ4P','manual');},'indicação duplicada amigável');$eventos=$auditoria->listar('indicacao',$id);iwAssert(array_column($eventos,'IAU_Acao')===['indicacao_criada','status_alterado'],'auditoria de criação e transição');$workflow->cancelarIndicacao($idManual,'cancelamento administrativo');$ev=$auditoria->listar('indicacao',$idManual);iwAssert(end($ev)['IAU_Acao']==='indicacao_cancelada','cancelamento auditado');
// Falha de auditoria deve reverter a indicação inteira.
$dbRollback=iwDb();$auditFalha=new class(new IndicacaoAuditoria($dbRollback)) extends IndicacaoAuditoriaService{public function registrar(array$d):int{throw new RuntimeException('falha controlada');}};[$wfRollback]=iwServices($dbRollback,null,$auditFalha);try{$wfRollback->registrarIndicacao(7,'ROD-8XJ4P','link');iwAssert(false,'falha deveria propagar');}catch(RuntimeException$e){}iwAssert((int)$dbRollback->query('SELECT COUNT(*) FROM indicacoes')->fetchColumn()===0,'rollback não deixa indicação sem auditoria');
// Simula duas requisições que disputam o mesmo indicado; a unique é a barreira final.
$dbRace=iwDb();$semPrecheck=new class($dbRace) extends Indicacao{public function buscarPorIndicado($id,$lock=false){return null;}};[$wfRace,$raceModel]=iwServices($dbRace,$semPrecheck);$wfRace->registrarIndicacao(8,'ROD-8XJ4P','link');iwDomain(function()use($wfRace){$wfRace->registrarIndicacao(8,'ROD-8XJ4P','manual');},'violação unique concorrente amigável');iwAssert((int)$dbRace->query('SELECT COUNT(*) FROM indicacoes WHERE CLI_Indicado_ID=8')->fetchColumn()===1,'concorrência mantém uma indicação');
echo "IndicacaoWorkflowTest OK\n";
