<?php
if(!extension_loaded('pdo_sqlite')){echo "IndicacaoElegibilidadeTest SKIP: pdo_sqlite indisponível\n";exit(0);}
$root=dirname(__DIR__);spl_autoload_register(function($c)use($root){foreach(['Models\\'=>'/app/Models/','Services\\'=>'/app/Services/','Core\\'=>'/app/Core/']as$p=>$d){if(strpos($c,$p)===0){$f=$root.$d.str_replace('\\','/',substr($c,strlen($p))).'.php';if(is_file($f))require_once$f;return;}}});
use Models\{Indicacao,IndicacaoAuditoria,IndicacaoCampanha,IndicacaoCodigo,IndicacaoCredito,TarefaAgendada};
use Services\TaskSchedulerService;
use Services\Indicacao\{IndicacaoAuditoriaService,IndicacaoCreditoService,IndicacaoElegibilidadeService,IndicacaoService};
use Services\Tasks\{IndicacaoConfirmacaoHandler,TaskPermanentFailureException,TaskRegistry,TaskRetryException};
function iea($v,$m){if(!$v){fwrite(STDERR,"FAIL: $m\n");exit(1);}}function iethrow(callable$f,$classe,$m){try{$f();iea(false,$m);}catch(Throwable$e){iea($e instanceof$classe,$m.' ('.get_class($e).')');}}
function iedb(){ $d=new PDO('sqlite::memory:');$d->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$d->exec("CREATE TABLE indicacao_campanhas(ICP_ID INTEGER PRIMARY KEY,ICP_Percentual REAL);CREATE TABLE indicacao_codigos(ICD_ID INTEGER PRIMARY KEY,CLI_ID INTEGER,ICP_ID INTEGER,ICD_Codigo TEXT,ICD_CodigoNormalizado TEXT,ICD_Status TEXT);CREATE TABLE indicacoes(IND_ID INTEGER PRIMARY KEY AUTOINCREMENT,ICD_ID INTEGER,ICP_ID INTEGER,CLI_Indicador_ID INTEGER,CLI_Indicado_ID INTEGER UNIQUE,IND_PercentualSnapshot REAL,IND_Origem TEXT,IND_Status TEXT,IND_CadastradaEm TEXT,IND_PagamentoConfirmadoEm TEXT,IND_ConfirmacaoAte TEXT,IND_AprovadaEm TEXT,IND_CanceladaEm TEXT,IND_FraudeEm TEXT,IND_InelegivelEm TEXT,IND_Motivo TEXT);CREATE TABLE indicacao_creditos(ICR_ID INTEGER PRIMARY KEY AUTOINCREMENT,IND_ID INTEGER UNIQUE,CLI_Indicador_ID INTEGER,ICP_ID INTEGER,ICR_Percentual REAL,ICR_Status TEXT,ICR_LiberadoEm TEXT,ICR_BloqueadoEm TEXT,ICR_CanceladoEm TEXT,ICR_ExpiradoEm TEXT,ICR_UtilizadoEm TEXT);CREATE TABLE indicacao_auditoria(IAU_ID INTEGER PRIMARY KEY AUTOINCREMENT,IAU_Entidade TEXT,IAU_EntidadeID INTEGER,IAU_Acao TEXT,IAU_StatusAnterior TEXT,IAU_StatusNovo TEXT,IAU_Motivo TEXT,USU_ID INTEGER,IAU_Correlacao TEXT,IAU_Dados TEXT,IAU_CriadoEm TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE tarefas_agendadas(TAG_ID INTEGER PRIMARY KEY AUTOINCREMENT,TAG_Tipo TEXT,TAG_Status TEXT,TAG_Prioridade INTEGER,TAG_ExecutarEm TEXT,TAG_Payload TEXT,TAG_ChaveIdempotencia TEXT UNIQUE,TAG_Tentativas INTEGER,TAG_MaxTentativas INTEGER,TAG_ProximaTentativaEm TEXT,TAG_ReservadaEm TEXT,TAG_LeaseAte TEXT,TAG_WorkerId TEXT,TAG_IniciadaEm TEXT,TAG_FinalizadaEm TEXT,TAG_UltimoErro TEXT,TAG_CriadaEm TEXT,TAG_AtualizadaEm TEXT);INSERT INTO indicacao_campanhas VALUES(1,15);INSERT INTO indicacoes(ICD_ID,ICP_ID,CLI_Indicador_ID,CLI_Indicado_ID,IND_PercentualSnapshot,IND_Origem,IND_Status,IND_CadastradaEm)VALUES(1,1,10,20,15,'link','aguardando_pagamento','2026-08-01 10:00:00');");return$d; }
function ies(PDO$db,DateTimeInterface$agora,$scheduler=null,$creditoService=null){$im=new Indicacao($db);$cm=new IndicacaoCredito($db);$audit=new IndicacaoAuditoriaService(new IndicacaoAuditoria($db));$is=new IndicacaoService($im,new IndicacaoCampanha($db),new IndicacaoCodigo($db),$audit,null,$db);$cs=$creditoService?:new IndicacaoCreditoService($cm,$im,$audit,null,$db);$scheduler=$scheduler?:new TaskSchedulerService(new TarefaAgendada($db),new TaskRegistry());return [new IndicacaoElegibilidadeService($db,$im,$cm,$is,$cs,$scheduler,function()use($agora){return$agora;}),$im,$cm,new IndicacaoAuditoria($db)];}
date_default_timezone_set('America/Sao_Paulo');$agora=new DateTimeImmutable('2026-08-07 15:00:00');$db=iedb();[$s,$im,$cm,$am]=ies($db,$agora);$pago=new DateTimeImmutable('2026-08-07 14:35:20');$r=$s->confirmarPrimeiroPagamento(20,$pago);$i=$im->buscar(1);iea($i['IND_Status']==='em_confirmacao','estado final em confirmação');iea($i['IND_PagamentoConfirmadoEm']==='2026-08-07 14:35:20','timestamp real preservado');iea($i['IND_ConfirmacaoAte']==='2026-08-14 14:35:20','sete dias completos');$t=$db->query('SELECT * FROM tarefas_agendadas')->fetch(PDO::FETCH_ASSOC);iea($t['TAG_ExecutarEm']==='2026-08-14 14:35:20','tarefa na data exata');iea($t['TAG_ChaveIdempotencia']==='indicacao_confirmacao_7d:1','chave idempotente');iea(json_decode($t['TAG_Payload'],true)===['indicacao_id'=>1],'payload mínimo');$s->confirmarPrimeiroPagamento(20,$pago);iea((int)$db->query('SELECT COUNT(*) FROM tarefas_agendadas')->fetchColumn()===1,'reprocessamento não duplica tarefa');
iethrow(function()use($s,$pago){$s->confirmarPrimeiroPagamento(999,$pago);},DomainException::class,'indicação inexistente');iethrow(function()use($s){$s->confirmarPrimeiroPagamento(20,new DateTimeImmutable('2026-09-01'));},InvalidArgumentException::class,'futuro absurdo rejeitado');$dbEstado=iedb();$dbEstado->exec("UPDATE indicacoes SET IND_Status='cancelada'");[$se]=ies($dbEstado,$agora);iethrow(function()use($se,$pago){$se->confirmarPrimeiroPagamento(20,$pago);},DomainException::class,'estado incompatível');
$dbFail=iedb();$falhaScheduler=new class extends TaskSchedulerService{public function __construct(){}public function agendar($t,array$p,DateTimeInterface$d,$c=null,$pr=100,$m=3):array{throw new RuntimeException('scheduler indisponível');}};[$sf]=ies($dbFail,$agora,$falhaScheduler);iethrow(function()use($sf,$pago){$sf->confirmarPrimeiroPagamento(20,$pago);},RuntimeException::class,'falha scheduler propaga');$if=(new Indicacao($dbFail))->buscar(1);iea($if['IND_Status']==='aguardando_pagamento'&&$if['IND_PagamentoConfirmadoEm']===null,'scheduler falho causa rollback');
$handler=new IndicacaoConfirmacaoHandler($s);iethrow(function()use($handler){$handler->executar(['indicacao_id'=>1]);},TaskRetryException::class,'execução antecipada retorna retry');iea($im->buscar(1)['IND_Status']==='em_confirmacao','antecipada não aprova');
[$apos,$im2,$cm2,$am2]=ies($db,new DateTimeImmutable('2026-08-14 14:35:20'));$handlerApos=new IndicacaoConfirmacaoHandler($apos);$handlerApos->executar(['indicacao_id'=>1]);$aprovada=$im2->buscar(1);$credito=$cm2->buscarPorIndicacao(1);iea($aprovada['IND_Status']==='aprovada'&&!empty($aprovada['IND_AprovadaEm']),'indicação aprovada');iea($credito['ICR_Status']==='liberado'&&!empty($credito['ICR_LiberadoEm']),'crédito liberado');iea((float)$credito['ICR_Percentual']===15.0,'percentual vem do snapshot');$db->exec('UPDATE indicacao_campanhas SET ICP_Percentual=99 WHERE ICP_ID=1');iea((float)$cm2->buscarPorIndicacao(1)['ICR_Percentual']===15.0,'campanha alterada não muda crédito');$handlerApos->executar(['indicacao_id'=>1]);iea((int)$db->query('SELECT COUNT(*) FROM indicacao_creditos')->fetchColumn()===1,'handler repetido é idempotente');$acoes=array_column($am2->listar('indicacao',1),'IAU_Acao');iea(in_array('primeiro_pagamento_confirmado',$acoes,true)&&in_array('confirmacao_iniciada',$acoes,true)&&in_array('indicacao_aprovada',$acoes,true),'auditoria da indicação');$cacoes=array_column($am2->listar('credito',$credito['ICR_ID']),'IAU_Acao');iea($cacoes===['credito_criado','status_alterado','credito_liberado'],'auditoria do crédito');
foreach(['cancelada','fraude','inelegivel']as$estado){$dx=iedb();$dx->exec("UPDATE indicacoes SET IND_Status='$estado',IND_PagamentoConfirmadoEm='2026-08-01',IND_ConfirmacaoAte='2026-08-08'");[$sx]=ies($dx,new DateTimeImmutable('2026-08-20'));$rx=$sx->processarConfirmacao(1);iea($rx['resultado']==='sem_acao'&&(int)$dx->query('SELECT COUNT(*) FROM indicacao_creditos')->fetchColumn()===0,"$estado sem crédito");}
$di=iedb();$di->exec("UPDATE indicacoes SET IND_Status='em_confirmacao',IND_PagamentoConfirmadoEm='2026-08-01',IND_ConfirmacaoAte='2026-08-08';INSERT INTO indicacao_creditos(IND_ID,CLI_Indicador_ID,ICP_ID,ICR_Percentual,ICR_Status)VALUES(1,10,1,15,'liberado')");[$si]=ies($di,new DateTimeImmutable('2026-08-20'));iethrow(function()use($si){$si->processarConfirmacao(1);},TaskPermanentFailureException::class,'crédito pré-existente é permanente');iethrow(function()use($si){$si->processarConfirmacao(404);},TaskPermanentFailureException::class,'indicação ausente é permanente');
$dr=iedb();$dr->exec("UPDATE indicacoes SET IND_Status='em_confirmacao',IND_PagamentoConfirmadoEm='2026-08-01',IND_ConfirmacaoAte='2026-08-08'");$imr=new Indicacao($dr);$cmr=new IndicacaoCredito($dr);$ar=new IndicacaoAuditoriaService(new IndicacaoAuditoria($dr));$csr=new class($cmr,$imr,$ar,null,$dr)extends IndicacaoCreditoService{public function criarPorIndicacao($id,$u=null,$s='pendente'):int{throw new RuntimeException('falha temporária');}};[$sr]=ies($dr,new DateTimeImmutable('2026-08-20'),null,$csr);iethrow(function()use($sr){$sr->processarConfirmacao(1);},TaskRetryException::class,'falha interna vira retry');iea((new Indicacao($dr))->buscar(1)['IND_Status']==='em_confirmacao'&&(int)$dr->query('SELECT COUNT(*) FROM indicacao_creditos')->fetchColumn()===0,'rollback aprovação/crédito');
$dc=iedb();$dc->exec("UPDATE indicacoes SET IND_Status='em_confirmacao',IND_PagamentoConfirmadoEm='2026-08-01',IND_ConfirmacaoAte='2026-08-08'");[$sc]=ies($dc,new DateTimeImmutable('2026-08-20'));$sc->processarConfirmacao(1);$sc->processarConfirmacao(1);iea((int)$dc->query('SELECT COUNT(*) FROM indicacao_creditos')->fetchColumn()===1,'dois workers não duplicam crédito');
echo "IndicacaoElegibilidadeTest OK\n";
