<?php
if(!extension_loaded('pdo_sqlite')){echo "IndicacaoReservasFinanceirasTest SKIP: pdo_sqlite indisponível\n";exit(0);}
$root=dirname(__DIR__);spl_autoload_register(function($c)use($root){foreach(['Models\\'=>'/app/Models/','Services\\'=>'/app/Services/','Core\\'=>'/app/Core/']as$p=>$d){if(strpos($c,$p)===0){$f=$root.$d.str_replace('\\','/',substr($c,strlen($p))).'.php';if(is_file($f))require_once$f;return;}}});
use Models\{Indicacao,IndicacaoAuditoria,IndicacaoCredito,IndicacaoCreditoReserva};use Services\{IndicacaoAuditoriaService,IndicacaoCreditoService,IndicacaoCreditoReservaService};use Services\Indicacao\{IndicacaoCalculoDescontoService,IndicacaoDescontoService};
function irf($v,$m){if(!$v){fwrite(STDERR,"FAIL: $m\n");exit(1);}}function irThrows(callable$f,$m){try{$f();irf(false,$m);}catch(Throwable$e){irf(strpos($e->getMessage(),'SQL')===false,$m);}}
function irDb(){ $d=new PDO('sqlite::memory:');$d->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$d->exec("CREATE TABLE indicacoes(IND_ID INTEGER PRIMARY KEY);CREATE TABLE indicacao_creditos(ICR_ID INTEGER PRIMARY KEY AUTOINCREMENT,IND_ID INTEGER UNIQUE,CLI_Indicador_ID INTEGER,ICP_ID INTEGER,ICR_Percentual TEXT,ICR_Status TEXT,ICR_LiberadoEm TEXT,ICR_BloqueadoEm TEXT,ICR_CanceladoEm TEXT,ICR_ExpiradoEm TEXT,ICR_UtilizadoEm TEXT);CREATE TABLE indicacao_credito_reservas(ICRR_ID INTEGER PRIMARY KEY AUTOINCREMENT,ICR_ID INTEGER,ICRR_ReferenciaTipo TEXT,ICRR_ReferenciaID TEXT,ICRR_Ciclo TEXT,ICRR_MesesCiclo INTEGER,ICRR_ValorBaseCicloCentavos INTEGER,ICRR_MensalidadeEquivalenteCentavos INTEGER,ICRR_Percentual TEXT,ICRR_DescontoCentavos INTEGER,ICRR_Status TEXT DEFAULT 'reservada',ICRR_ReservadoEm TEXT,ICRR_UtilizadoEm TEXT,ICRR_LiberadoEm TEXT,ICRR_CanceladoEm TEXT,ICRR_CriadoEm TEXT DEFAULT CURRENT_TIMESTAMP,ICRR_AtualizadoEm TEXT,ICRR_CreditoAtivo INTEGER GENERATED ALWAYS AS(CASE WHEN ICRR_Status='reservada' THEN ICR_ID END) STORED,UNIQUE(ICRR_CreditoAtivo),UNIQUE(ICRR_ReferenciaTipo,ICRR_ReferenciaID,ICR_ID));CREATE TABLE indicacao_auditoria(IAU_ID INTEGER PRIMARY KEY AUTOINCREMENT,IAU_Entidade TEXT,IAU_EntidadeID INTEGER,IAU_Acao TEXT,IAU_StatusAnterior TEXT,IAU_StatusNovo TEXT,IAU_Motivo TEXT,USU_ID INTEGER,IAU_Correlacao TEXT,IAU_Dados TEXT,IAU_CriadoEm TEXT DEFAULT CURRENT_TIMESTAMP);");return$d;}
function irCreditos(PDO$d,$q,array$p=[15],$cliente=1){for($i=0;$i<$q;$i++){$pct=(string)($p[$i%count($p)]);$data=sprintf('2026-08-%02d 10:00:00',$i+1);$s=$d->prepare("INSERT INTO indicacao_creditos(IND_ID,CLI_Indicador_ID,ICP_ID,ICR_Percentual,ICR_Status,ICR_LiberadoEm)VALUES(?,?,?,?, 'liberado',?)");$s->execute([$i+1,$cliente,1,$pct,$data]);}}
function irService(PDO$d,$reservaModel=null,$creditoModel=null,$audit=null){$rm=$reservaModel?:new IndicacaoCreditoReserva($d);$cm=$creditoModel?:new IndicacaoCredito($d);$audit=$audit?:new IndicacaoAuditoriaService(new IndicacaoAuditoria($d));$cs=new IndicacaoCreditoService($d,$cm,new Indicacao($d),$audit);$rs=new IndicacaoCreditoReservaService($d,$rm,$cs,$audit);return [new IndicacaoDescontoService($d,$cm,$rm,$rs,new IndicacaoCalculoDescontoService()),$rm,$cm];}
// Cálculo central, exemplos oficiais e arredondamento distribuído.
$calc=new IndicacaoCalculoDescontoService();irf($calc->meses('mensal')===1&&$calc->meses('trimestral')===3&&$calc->meses('semestral')===6&&$calc->meses('anual')===12,'ciclos centralizados');irThrows(function()use($calc){$calc->meses('bienal');},'ciclo inválido');$dist=$calc->distribuirMensalidades(10001,3);irf($dist===[3334,3334,3333]&&array_sum($dist)===10001,'resto distribuído sem perder centavos');
$d=irDb();irCreditos($d,2,[15]);[$s]=irService($d);$r=$s->prepararDesconto(1,'trimestral',27000,'cobranca','tri-270');irf($r['mensalidade_equivalente_centavos']===9000&&$r['desconto_total_centavos']===2700&&$r['valor_final_centavos']===24300,'exemplo trimestral 27000');
$d2=irDb();irCreditos($d2,2,[15,10]);[$s2]=irService($d2);$r2=$s2->prepararDesconto(1,'trimestral',30000,'cobranca','percentuais');irf(array_column($r2['reservas'],'desconto_centavos')===[1500,1000]&&$r2['valor_final_centavos']===27500,'percentuais históricos individuais');
// Matriz de limites dos ciclos, incluindo zero, abaixo, igual e acima.
foreach([['mensal',1,[0,1,4]],['trimestral',3,[1,2,3,5]],['semestral',6,[4,6,8]],['anual',12,[10,12,15]]]as[$ciclo,$max,$quantidades])foreach($quantidades as$q){$dx=irDb();irCreditos($dx,$q);[$sx]=irService($dx);$rx=$sx->prepararDesconto(1,$ciclo,$max*10000,'teste',"$ciclo-$q");irf($rx['quantidade_creditos']===min($q,$max),"limite $ciclo com $q");irf((int)$dx->query("SELECT COUNT(*) FROM indicacao_creditos WHERE ICR_Status='liberado'")->fetchColumn()===max(0,$q-$max),'excedentes permanecem liberados');}
// FIFO e idempotência por referência congelam conjunto e valores.
$df=irDb();irCreditos($df,3,[15,10,20]);[$sf]=$tmp=irService($df);$a=$sf->prepararDesconto(1,'trimestral',30000,'cobranca','fifo');$ids=array_column($a['reservas'],'credito_id');irf($ids===[1,2,3],'FIFO por data e ID');$b=$sf->prepararDesconto(1,'trimestral',99999,'cobranca','fifo');irf($b['valor_base_centavos']===30000&&array_column($b['reservas'],'credito_id')===$ids,'reprocessamento devolve snapshot original');irf((int)$df->query('SELECT COUNT(*) FROM indicacao_credito_reservas')->fetchColumn()===3,'idempotência não duplica reservas');
// Utilização integral e idempotente.
$u=$sf->confirmarUtilizacao('cobranca','fifo');irf(count(array_filter(array_column($u['reservas'],'status'),fn($x)=>$x==='utilizada'))===3,'todas reservas utilizadas');irf((int)$df->query("SELECT COUNT(*) FROM indicacao_creditos WHERE ICR_Status='utilizado'")->fetchColumn()===3,'todos créditos utilizados');$sf->confirmarUtilizacao('cobranca','fifo');
// Liberação integral preserva a data FIFO e impede confirmação posterior.
$dl=irDb();irCreditos($dl,2);$datas=$dl->query('SELECT ICR_LiberadoEm FROM indicacao_creditos ORDER BY ICR_ID')->fetchAll(PDO::FETCH_COLUMN);[$sl]=irService($dl);$sl->prepararDesconto(1,'trimestral',30000,'cobranca','liberar');$l=$sl->liberarReservas('cobranca','liberar','vencimento');irf(count(array_filter(array_column($l['reservas'],'status'),fn($x)=>$x==='liberada'))===2,'todas reservas liberadas');irf($dl->query('SELECT ICR_LiberadoEm FROM indicacao_creditos ORDER BY ICR_ID')->fetchAll(PDO::FETCH_COLUMN)===$datas,'FIFO original preservado');$sl->liberarReservas('cobranca','liberar','reprocessamento');irThrows(function()use($sl){$sl->confirmarUtilizacao('cobranca','liberar');},'não confirma referência liberada');
// Referências diferentes disputando o mesmo crédito: somente a primeira reserva.
$dc=irDb();irCreditos($dc,1);[$sc]=irService($dc);$x=$sc->prepararDesconto(1,'mensal',10000,'cobranca','A');$y=$sc->prepararDesconto(1,'mensal',10000,'cobranca','B');irf($x['quantidade_creditos']===1&&$y['quantidade_creditos']===0,'crédito não é reservado duas vezes');try{$dc->exec("INSERT INTO indicacao_credito_reservas(ICR_ID,ICRR_ReferenciaTipo,ICRR_ReferenciaID,ICRR_Ciclo,ICRR_MesesCiclo,ICRR_ValorBaseCicloCentavos,ICRR_MensalidadeEquivalenteCentavos,ICRR_Percentual,ICRR_DescontoCentavos,ICRR_Status,ICRR_ReservadoEm)VALUES(1,'cobranca','C','mensal',1,10000,10000,15,1500,'reservada','2026-08-01')");irf(false,'banco bloqueia segunda reserva ativa');}catch(PDOException$e){}
// Falha na segunda inserção reverte reservas, estados e auditoria.
$dr=irDb();irCreditos($dr,3);$rm=new class($dr)extends IndicacaoCreditoReserva{private $n=0;public function inserir(array$d):int{if(++$this->n===2)throw new RuntimeException('falha segunda reserva');return parent::inserir($d);}};[$sr]=irService($dr,$rm);irThrows(function()use($sr){$sr->prepararDesconto(1,'trimestral',30000,'cobranca','rollback');},'falha intermediária');irf((int)$dr->query('SELECT COUNT(*) FROM indicacao_credito_reservas')->fetchColumn()===0&&(int)$dr->query("SELECT COUNT(*) FROM indicacao_creditos WHERE ICR_Status='liberado'")->fetchColumn()===3,'rollback não deixa estado parcial');
// Falha de auditoria também reverte.
$da=irDb();irCreditos($da,2);$auditFalha=new class(new IndicacaoAuditoria($da))extends IndicacaoAuditoriaService{public function registrar(array$d):int{throw new RuntimeException('auditoria falhou');}};[$sa]=irService($da,null,null,$auditFalha);irThrows(function()use($sa){$sa->prepararDesconto(1,'trimestral',30000,'cobranca','audit');},'falha auditoria');irf((int)$da->query('SELECT COUNT(*) FROM indicacao_credito_reservas')->fetchColumn()===0&&(int)$da->query("SELECT COUNT(*) FROM indicacao_creditos WHERE ICR_Status='liberado'")->fetchColumn()===2,'rollback de auditoria');
// Falha na mudança de estado do segundo crédito também desfaz o lote inteiro.
$ds=irDb();irCreditos($ds,2);$cmFalha=new class($ds)extends IndicacaoCredito{private$n=0;public function status($id,$a,$novo):bool{if($novo==='reservado'&&++$this->n===2)return false;return parent::status($id,$a,$novo);}};[$ss]=irService($ds,null,$cmFalha);irThrows(function()use($ss){$ss->prepararDesconto(1,'trimestral',30000,'cobranca','status');},'falha de estado');irf((int)$ds->query('SELECT COUNT(*) FROM indicacao_credito_reservas')->fetchColumn()===0&&(int)$ds->query("SELECT COUNT(*) FROM indicacao_creditos WHERE ICR_Status='liberado'")->fetchColumn()===2,'rollback da mudança de estado');
$acoes=array_column((new IndicacaoAuditoria($dl))->listar('credito_reserva',1),'IAU_Acao');irf(in_array('reserva_criada',$acoes,true)&&in_array('reserva_liberada',$acoes,true),'auditoria de reserva');
echo "IndicacaoReservasFinanceirasTest OK\n";
