<?php
if(!extension_loaded('pdo_sqlite')){echo "IndicacaoDominioTest SKIP: pdo_sqlite indisponível\n";exit(0);}
$root=dirname(__DIR__); spl_autoload_register(function($classe)use($root){$mapa=['Models\\'=>$root.'/app/Models/','Services\\'=>$root.'/app/Services/','Core\\'=>$root.'/app/Core/'];foreach($mapa as $prefixo=>$base){if(strpos($classe,$prefixo)===0){$arquivo=$base.str_replace('\\','/',substr($classe,strlen($prefixo))).'.php';if(is_file($arquivo))require_once $arquivo;return;}}});
use Models\{IndicacaoAuditoria,IndicacaoCampanha,IndicacaoCodigo,Indicacao,IndicacaoCredito};
use Services\{IndicacaoAuditoriaService,IndicacaoCampanhaService,IndicacaoCodigoService,IndicacaoService,IndicacaoCreditoService};
use Services\Indicacao\{CodigoIndicacaoPadraoGenerator,CodigoIndicacaoGeneratorInterface,CodigoIndicacaoNormalizer,IndicacaoStatusTransitionService};
function ia($ok,$m){if(!$ok){fwrite(STDERR,"FAIL: $m\n");exit(1);}}
$db=new PDO('sqlite::memory:');$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$db->exec("PRAGMA foreign_keys=ON;
CREATE TABLE indicacao_campanhas(ICP_ID INTEGER PRIMARY KEY AUTOINCREMENT,ICP_Nome TEXT,ICP_Descricao TEXT,ICP_Percentual REAL CHECK(ICP_Percentual>0 AND ICP_Percentual<=100),ICP_DataInicio TEXT,ICP_DataFim TEXT,ICP_Ativo TEXT DEFAULT 'N',ICP_Publica TEXT,ICP_RegrasSnapshot TEXT,ICP_CriadoPor_USU_ID INTEGER,ICP_CriadoEm TEXT DEFAULT CURRENT_TIMESTAMP,ICP_AtualizadoEm TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX unica_publica_ativa ON indicacao_campanhas((CASE WHEN ICP_Ativo='S' AND ICP_Publica='S' THEN 1 END));
CREATE TABLE indicacao_codigos(ICD_ID INTEGER PRIMARY KEY AUTOINCREMENT,CLI_ID INTEGER,ICP_ID INTEGER,ICD_Codigo TEXT,ICD_CodigoNormalizado TEXT UNIQUE,ICD_Status TEXT DEFAULT 'nao_liberado',ICD_LiberadoEm TEXT,ICD_SuspensoEm TEXT,ICD_CanceladoEm TEXT,ICD_CriadoEm TEXT DEFAULT CURRENT_TIMESTAMP,ICD_AtualizadoEm TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(CLI_ID,ICP_ID));
CREATE TABLE indicacoes(IND_ID INTEGER PRIMARY KEY AUTOINCREMENT,ICD_ID INTEGER,ICP_ID INTEGER,CLI_Indicador_ID INTEGER,CLI_Indicado_ID INTEGER UNIQUE,IND_PercentualSnapshot REAL,IND_Origem TEXT,IND_Status TEXT DEFAULT 'cadastrada',IND_CadastradaEm TEXT,IND_PagamentoConfirmadoEm TEXT,IND_ConfirmacaoAte TEXT,IND_AprovadaEm TEXT,IND_CanceladaEm TEXT,IND_FraudeEm TEXT,IND_InelegivelEm TEXT,IND_Motivo TEXT,IND_CriadaEm TEXT DEFAULT CURRENT_TIMESTAMP,IND_AtualizadaEm TEXT DEFAULT CURRENT_TIMESTAMP,UNIQUE(ICD_ID,CLI_Indicado_ID));
CREATE TABLE indicacao_creditos(ICR_ID INTEGER PRIMARY KEY AUTOINCREMENT,IND_ID INTEGER UNIQUE,CLI_Indicador_ID INTEGER,ICP_ID INTEGER,ICR_Percentual REAL,ICR_Status TEXT DEFAULT 'pendente',ICR_LiberadoEm TEXT,ICR_BloqueadoEm TEXT,ICR_CanceladoEm TEXT,ICR_ExpiradoEm TEXT,ICR_UtilizadoEm TEXT,ICR_CriadoEm TEXT DEFAULT CURRENT_TIMESTAMP,ICR_AtualizadoEm TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE indicacao_auditoria(IAU_ID INTEGER PRIMARY KEY AUTOINCREMENT,IAU_Entidade TEXT,IAU_EntidadeID INTEGER,IAU_Acao TEXT,IAU_StatusAnterior TEXT,IAU_StatusNovo TEXT,IAU_Motivo TEXT,USU_ID INTEGER,IAU_Correlacao TEXT,IAU_Dados TEXT,IAU_CriadoEm TEXT DEFAULT CURRENT_TIMESTAMP);");
$aModel=new IndicacaoAuditoria($db);$audit=new IndicacaoAuditoriaService($aModel);$cModel=new IndicacaoCampanha($db);$camp=new IndicacaoCampanhaService($db,$cModel,$audit);
$dados=['nome'=>'Inicial','percentual'=>15,'data_inicio'=>'2026-08-07 00:00:00','publica'=>true,'regras'=>['versao'=>1]];$c1=$camp->criar($dados);ia($c1>0,'cria campanha configurável');$camp->ativar($c1);ia($cModel->buscarPublicaAtiva()['ICP_Percentual']==15,'ativa campanha pública');
try{$camp->criar(array_replace($dados,['percentual'=>0]));ia(false,'percentual zero rejeitado');}catch(InvalidArgumentException $e){}try{$camp->criar(array_replace($dados,['percentual'=>101]));ia(false,'percentual >100 rejeitado');}catch(InvalidArgumentException $e){}
$c2=$camp->criar(array_replace($dados,['nome'=>'Outra']));$camp->editar($c2,array_replace($dados,['nome'=>'Outra futura']));ia($cModel->buscar($c2)['ICP_Nome']==='Outra futura','edita campanha futura');try{$camp->ativar($c2);ia(false,'segunda pública ativa rejeitada');}catch(DomainException $e){}$camp->inativar($c1);$camp->ativar($c2);ia($cModel->buscar($c1)!==null,'histórico de campanha preservado');try{$camp->editar($c2,$dados);ia(false,'campanha ativa não pode reescrever histórico');}catch(DomainException $e){}
$gen=new CodigoIndicacaoPadraoGenerator();ia($gen->prefixo(['nome_fantasia'=>'Rodrigo Silva Costa'])==='RSC','prefixo composto');ia($gen->prefixo(['nome_fantasia'=>'','razao_social'=>'Áurea'])==='AUR','acentos e fallback de campo');ia($gen->prefixo(['nome'=>'Lu'])==='LUX','nome curto');ia($gen->prefixo([])==='DSP','fallback');for($i=0;$i<50;$i++){ia((bool)preg_match('/^[A-Z0-9]{3}-[ABCDEFGHJKLMNPQRSTUVWXYZ23456789]{5}$/',$gen->gerar(['nome'=>'Teste'])),'sufixo seguro sem ambíguos');}
ia(CodigoIndicacaoNormalizer::normalizar(' rod-8xj4p ')==='ROD8XJ4P','normalização central');
$sequencial=new class implements CodigoIndicacaoGeneratorInterface{private $i=0;public function gerar(array $c):string{return ++$this->i<3?'TES-ABCDE':'TES-BCDEF';}};$codModel=new IndicacaoCodigo($db);$db->exec("INSERT INTO indicacao_codigos(CLI_ID,ICP_ID,ICD_Codigo,ICD_CodigoNormalizado)VALUES(90,90,'TES-ABCDE','TESABCDE')");$codSvc=new IndicacaoCodigoService($db,$codModel,$audit,$sequencial,4);$codigo=$codSvc->criar(1,$c2,['nome'=>'Teste']);ia($codModel->buscar($codigo)['ICD_Codigo']==='TES-BCDEF','retry de colisão');ia($codSvc->buscar('tes-bcdef')['ICD_ID']==$codigo,'consulta case-insensitive normalizada');$codSvc->transicionar($codigo,'ativo');
$iModel=new Indicacao($db);$iSvc=new IndicacaoService($db,$iModel,$cModel,$audit);$ind=$iSvc->criar(['codigo_id'=>$codigo,'campanha_id'=>$c2,'indicador_id'=>1,'indicado_id'=>2,'origem'=>'link']);ia((float)$iModel->buscar($ind)['IND_PercentualSnapshot']===15.0,'snapshot da campanha');try{$iSvc->criar(['codigo_id'=>$codigo,'campanha_id'=>$c2,'indicador_id'=>2,'indicado_id'=>2,'origem'=>'manual']);ia(false,'autoindicação rejeitada');}catch(DomainException $e){}try{$iSvc->criar(['codigo_id'=>$codigo,'campanha_id'=>$c2,'indicador_id'=>3,'indicado_id'=>2,'origem'=>'manual']);ia(false,'indicado duplicado rejeitado');}catch(PDOException $e){}
$iSvc->transicionar($ind,'aguardando_pagamento');try{$iSvc->transicionar($ind,'aprovada');ia(false,'transição arbitrária rejeitada');}catch(DomainException $e){}
$crModel=new IndicacaoCredito($db);$crSvc=new IndicacaoCreditoService($db,$crModel,$iModel,$audit);$cr=$crSvc->criar($ind);ia((float)$crModel->buscar($cr)['ICR_Percentual']===15.0,'snapshot copiado ao crédito');try{$crSvc->criar($ind);ia(false,'um crédito por indicação');}catch(PDOException $e){}$crSvc->transicionar($cr,'em_confirmacao');$crSvc->transicionar($cr,'liberado');ia($crSvc->disponiveisFifo(1)[0]['ICR_ID']==$cr,'FIFO por liberação e ID');
$audit->registrar(['entidade'=>'teste','entidade_id'=>1,'acao'=>'seguranca','motivo'=>'token=secreto senha=privada','dados'=>['payload'=>'bruto','origem'=>'teste']]);$eventosTeste=$aModel->listar('teste',1);$linha=end($eventosTeste);$serial=json_encode($linha);ia(strpos($serial,'secreto')===false&&strpos($serial,'privada')===false&&strpos($serial,'bruto')===false,'auditoria sanitizada');ia(count($aModel->listar('campanha',$c1))>=2,'mutações auditadas');
echo "IndicacaoDominioTest OK\n";
