<?php
if(!extension_loaded('pdo_sqlite')){echo "IndicacaoReservasFinanceirasTest SKIP: pdo_sqlite indisponível\n";exit(0);}
$root=dirname(__DIR__);spl_autoload_register(function($c)use($root){foreach(['Models\\'=>'/app/Models/','Services\\'=>'/app/Services/','Core\\'=>'/app/Core/']as$p=>$d){if(strpos($c,$p)===0){$f=$root.$d.str_replace('\\','/',substr($c,strlen($p))).'.php';if(is_file($f))require_once$f;return;}}});
use Models\{Indicacao,IndicacaoAuditoria,IndicacaoCredito,IndicacaoCreditoReserva};
use Services\Indicacao\{IndicacaoAuditoriaService,IndicacaoCalculoDescontoService,IndicacaoCreditoReservaService,IndicacaoCreditoService,IndicacaoDescontoService};
function irf($v,$m){if(!$v){fwrite(STDERR,"FAIL: $m\n");exit(1);}}function irThrows(callable$f,$m){try{$f();irf(false,$m);}catch(Throwable$e){irf(strpos($e->getMessage(),'SQL')===false,$m);}}
function irDb(){ $d=new PDO('sqlite::memory:');$d->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$d->exec("CREATE TABLE indicacoes(IND_ID INTEGER PRIMARY KEY);CREATE TABLE indicacao_creditos(ICR_ID INTEGER PRIMARY KEY AUTOINCREMENT,IND_ID INTEGER UNIQUE,CLI_Indicador_ID INTEGER,ICP_ID INTEGER,ICR_Percentual TEXT,ICR_Status TEXT,ICR_LiberadoEm TEXT,ICR_BloqueadoEm TEXT,ICR_CanceladoEm TEXT,ICR_ExpiradoEm TEXT,ICR_UtilizadoEm TEXT);CREATE TABLE indicacao_credito_reservas(ICRR_ID INTEGER PRIMARY KEY AUTOINCREMENT,ICR_ID INTEGER,ICRR_ReferenciaTipo TEXT,ICRR_ReferenciaID TEXT,ICRR_Ciclo TEXT,ICRR_MesesCiclo INTEGER,ICRR_ValorBaseCicloCentavos INTEGER,ICRR_MensalidadeEquivalenteCentavos INTEGER,ICRR_Percentual TEXT,ICRR_DescontoCentavos INTEGER,ICRR_Status TEXT DEFAULT 'reservada',ICRR_ReservadoEm TEXT,ICRR_UtilizadoEm TEXT,ICRR_LiberadoEm TEXT,ICRR_CanceladoEm TEXT,ICRR_CriadoEm TEXT DEFAULT CURRENT_TIMESTAMP,ICRR_AtualizadoEm TEXT,ICRR_CreditoAtivo INTEGER GENERATED ALWAYS AS(CASE WHEN ICRR_Status='reservada' THEN ICR_ID END) STORED,UNIQUE(ICRR_CreditoAtivo),UNIQUE(ICRR_ReferenciaTipo,ICRR_ReferenciaID,ICR_ID));CREATE TABLE indicacao_auditoria(IAU_ID INTEGER PRIMARY KEY AUTOINCREMENT,IAU_Entidade TEXT,IAU_EntidadeID INTEGER,IAU_Acao TEXT,IAU_StatusAnterior TEXT,IAU_StatusNovo TEXT,IAU_Motivo TEXT,USU_ID INTEGER,IAU_Correlacao TEXT,IAU_Dados TEXT,IAU_CriadoEm TEXT DEFAULT CURRENT_TIMESTAMP);");return$d;}
function irCreditos(PDO$d,$q,array$p=[15],$cliente=1){for($i=0;$i<$q;$i++){$pct=(string)$p[$i%count($p)];$data=sprintf('2026-08-%02d 10:00:00',$i+1);$s=$d->prepare("INSERT INTO indicacao_creditos(IND_ID,CLI_Indicador_ID,ICP_ID,ICR_Percentual,ICR_Status,ICR_LiberadoEm)VALUES(?,?,?,?, 'liberado',?)");$s->execute([$i+1,$cliente,1,$pct,$data]);}}
function irService(PDO$d){$rm=new IndicacaoCreditoReserva($d);$cm=new IndicacaoCredito($d);$audit=new IndicacaoAuditoriaService(new IndicacaoAuditoria($d));$cs=new IndicacaoCreditoService($cm,new Indicacao($d),$audit,null,$d);$rs=new IndicacaoCreditoReservaService($d,$rm,$cs,$audit);return[new IndicacaoDescontoService($d,$cm,$rm,$rs,new IndicacaoCalculoDescontoService()),$rm,$cm];}
$calc=new IndicacaoCalculoDescontoService();irf($calc->meses('mensal')===1&&$calc->meses('trimestral')===3&&$calc->meses('semestral')===6&&$calc->meses('anual')===12,'ciclos centralizados');$dist=$calc->distribuirMensalidades(10001,3);irf($dist===[3334,3334,3333]&&array_sum($dist)===10001,'resto distribuído');
$d=irDb();irCreditos($d,2,[15]);[$s]=irService($d);$r=$s->prepararDesconto(1,'trimestral',27000,'cobranca','tri-270');irf($r['desconto_total_centavos']===2700&&$r['valor_final_centavos']===24300,'exemplo 27000');
$d2=irDb();irCreditos($d2,2,[15,10]);[$s2]=irService($d2);$r2=$s2->prepararDesconto(1,'trimestral',30000,'cobranca','percentuais');irf(array_column($r2['reservas'],'desconto_centavos')===[1500,1000]&&$r2['valor_final_centavos']===27500,'percentuais históricos');
foreach([['mensal',1,4],['trimestral',3,5],['semestral',6,8],['anual',12,15]]as[$ciclo,$max,$q]){$dx=irDb();irCreditos($dx,$q);[$sx]=irService($dx);$rx=$sx->prepararDesconto(1,$ciclo,$max*10000,'teste',$ciclo);irf($rx['quantidade_creditos']===$max,"limite $ciclo");irf((int)$dx->query("SELECT COUNT(*) FROM indicacao_creditos WHERE ICR_Status='liberado'")->fetchColumn()===$q-$max,'excedentes liberados');}
$df=irDb();irCreditos($df,3,[15,10,20]);[$sf]=irService($df);$a=$sf->prepararDesconto(1,'trimestral',30000,'cobranca','fifo');irf(array_column($a['reservas'],'credito_id')===[1,2,3],'FIFO');$b=$sf->prepararDesconto(1,'trimestral',99999,'cobranca','fifo');irf($b['valor_base_centavos']===30000&&$b['desconto_total_centavos']===$a['desconto_total_centavos'],'idempotência por referência');
$u=$sf->confirmarUtilizacao('cobranca','fifo');irf(count(array_filter(array_column($u['reservas'],'status'),fn($x)=>$x==='utilizada'))===3,'utilização integral');$sf->confirmarUtilizacao('cobranca','fifo');
$dl=irDb();irCreditos($dl,2);$datas=$dl->query('SELECT ICR_LiberadoEm FROM indicacao_creditos ORDER BY ICR_ID')->fetchAll(PDO::FETCH_COLUMN);[$sl]=irService($dl);$sl->prepararDesconto(1,'trimestral',30000,'cobranca','liberar');$l=$sl->liberarReservas('cobranca','liberar','vencimento');irf(count(array_filter(array_column($l['reservas'],'status'),fn($x)=>$x==='liberada'))===2,'liberação integral');irf($dl->query('SELECT ICR_LiberadoEm FROM indicacao_creditos ORDER BY ICR_ID')->fetchAll(PDO::FETCH_COLUMN)===$datas,'FIFO original preservado');irThrows(function()use($sl){$sl->confirmarUtilizacao('cobranca','liberar');},'não confirma referência liberada');
$dc=irDb();irCreditos($dc,1);[$sc]=irService($dc);$x=$sc->prepararDesconto(1,'mensal',10000,'cobranca','A');$y=$sc->prepararDesconto(1,'mensal',10000,'cobranca','B');irf($x['quantidade_creditos']===1&&$y['quantidade_creditos']===0,'crédito não duplica reserva ativa');
echo "IndicacaoReservasFinanceirasTest OK\n";
