<?php
use Core\Session;
$flash=Session::getFlash();
function pciEsc($v){return htmlspecialchars((string)($v??''),ENT_QUOTES,'UTF-8');}
?>
<!doctype html><html lang="pt-br"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cadastro | Disparador.net</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"><link rel="stylesheet" href="<?= ASSET_URL ?>/css/style.css?v=12"></head><body class="site-cadastro-page"><div class="container py-5">
<div class="text-center mb-4"><img src="<?= ASSET_URL ?>/img/logo-disparador.png" alt="Disparador.net" style="max-height:85px;max-width:320px"></div><div class="row justify-content-center"><div class="col-xl-9"><div class="card"><div class="card-body p-4 p-md-5">
<?php if(!$convite){ ?><div class="alert alert-danger">Este convite é inválido, expirou ou já foi utilizado.</div><?php }else{ ?>
<span class="badge badge-primary mb-3">Convite Partner</span><h2>Conecte sua empresa ao Disparador.net</h2><p class="text-muted">Você foi convidado por <strong><?= pciEsc($convite['PAR_Nome']) ?></strong>. Após o cadastro, você poderá conectar seu WhatsApp e gerenciar os templates da sua empresa.</p>
<?php if($flash){ ?><div class="alert alert-<?= $flash['type']==='error'?'danger':'success' ?>"><?= pciEsc($flash['message']) ?></div><?php } ?>
<form method="post" action="<?= BASE_URL ?>/index.php?url=parceiroConvite/salvar" id="formClientePartner"><?= \Core\Csrf::input() ?><input type="hidden" name="convite_token" value="<?= pciEsc($token) ?>">
<h5 class="mt-4">Empresa e responsável</h5><div class="row">
<div class="form-group col-md-6"><label>Nome da empresa / marca</label><input name="nome" class="form-control" required></div><div class="form-group col-md-6"><label>Razão social</label><input name="razao_social" class="form-control" required></div>
<div class="form-group col-md-6"><label>Nome fantasia</label><input name="nome_fantasia" class="form-control"></div><div class="form-group col-md-6"><label>CNPJ</label><input name="cnpj" id="pciCnpj" class="form-control" required maxlength="18"></div>
<div class="form-group col-md-6"><label>Responsável</label><input name="responsavel" class="form-control" required></div><div class="form-group col-md-6"><label>WhatsApp / telefone</label><input name="telefone" id="pciTelefone" class="form-control" required></div>
<div class="form-group col-md-6"><label>E-mail de acesso</label><input type="email" name="email" id="pciEmail" class="form-control text-lowercase" required></div></div>
<h5 class="mt-4">Endereço</h5><div class="row"><div class="form-group col-md-3"><label>CEP</label><input name="cep" id="pciCep" class="form-control" required maxlength="9"><small id="pciCepStatus" class="text-muted"></small></div><div class="form-group col-md-7"><label>Logradouro</label><input name="logradouro" id="pciLogradouro" class="form-control" required></div><div class="form-group col-md-2"><label>Número</label><input name="numero" id="pciNumero" class="form-control" required></div>
<div class="form-group col-md-4"><label>Complemento</label><input name="complemento" class="form-control"></div><div class="form-group col-md-4"><label>Bairro</label><input name="bairro" id="pciBairro" class="form-control" required></div><div class="form-group col-md-4"><label>Município</label><input name="municipio" id="pciMunicipio" class="form-control" required></div><div class="form-group col-md-2"><label>UF</label><input name="uf" id="pciUf" class="form-control text-uppercase" maxlength="2" required></div><div class="form-group col-md-3"><label>Código IBGE</label><input name="codigo_ibge" id="pciIbge" class="form-control" maxlength="7" required></div></div>
<h5 class="mt-4">Acesso</h5><div class="row"><div class="form-group col-md-6"><label>Senha</label><input type="password" name="senha" id="pciSenha" class="form-control" data-password-strength minlength="8" required></div><div class="form-group col-md-6"><label>Confirmar senha</label><input type="password" name="confirmar_senha" class="form-control" data-password-confirm="#pciSenha" required></div></div>
<div class="form-check mb-4"><input class="form-check-input" type="checkbox" name="aceite_termos" id="pciTermos" required><label class="form-check-label" for="pciTermos">Li e concordo com os <a target="_blank" href="<?= BASE_URL ?>/index.php?url=site/termosUso">Termos de Uso</a> e a <a target="_blank" href="<?= BASE_URL ?>/index.php?url=site/politicaPrivacidade">Política de Privacidade</a>.</label></div>
<button class="btn btn-primary btn-lg btn-block">Criar minha conta</button></form><?php } ?></div></div></div></div></div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.inputmask/5.0.8/jquery.inputmask.min.js"></script><script>
$(function(){function n(v){return String(v||'').replace(/\D/g,'');}$('#pciCnpj').inputmask('99.999.999/9999-99');$('#pciTelefone').inputmask('(99) 99999-9999');$('#pciCep').inputmask('99999-999');$('#pciEmail').on('input',function(){this.value=this.value.toLowerCase();});$('#pciCep').on('blur',function(){var cep=n(this.value);if(cep.length!==8)return;$('#pciCepStatus').text('Consultando CEP...');$.getJSON('https://viacep.com.br/ws/'+cep+'/json/').done(function(d){if(d.erro){$('#pciCepStatus').text('CEP não encontrado.');return;}$('#pciLogradouro').val(d.logradouro||'');$('#pciBairro').val(d.bairro||'');$('#pciMunicipio').val(d.localidade||'');$('#pciUf').val(d.uf||'');$('#pciIbge').val(d.ibge||'');$('#pciCepStatus').text('Endereço localizado. Confira os dados.');$('#pciNumero').focus();}).fail(function(){$('#pciCepStatus').text('Não foi possível consultar o CEP. Preencha manualmente.');});});});
</script><script src="<?= ASSET_URL ?>/js/password-strength.js"></script></body></html>
