<div class="card"><div class="card-header"><h3 class="card-title"><?= htmlspecialchars($parceiro['PAR_Nome']) ?> — <?= htmlspecialchars($parceiro['PAR_Identificador']) ?></h3></div><div class="card-body">
<p><strong>Cadastro partner:</strong> <?= htmlspecialchars($parceiro['CLI_Nome']) ?> (#<?= (int)$parceiro['CLI_ID'] ?>)</p>
<p><strong>Status:</strong> <?php if(($parceiro['PAR_StatusCadastro']??'')==='aprovado'){ ?><span class="badge badge-success">Aprovado</span><?php }else{ ?><span class="badge badge-warning">Pendente de aprovação</span><?php } ?></p>
<?php if(($parceiro['PAR_StatusCadastro']??'')!=='aprovado'){ ?><div class="alert alert-warning">Este parceiro ainda não pode receber credenciais da API.<form method="post" action="<?= BASE_URL ?>/index.php?url=parceiroAdmin/aprovar" class="mt-2 mb-0" onsubmit="return confirm('Aprovar este cadastro Partner?')"><?= \Core\Csrf::input(); ?><input type="hidden" name="parceiro_id" value="<?= (int)$parceiro['PAR_ID'] ?>"><button class="btn btn-success btn-sm"><i class="fas fa-check mr-1"></i>Aprovar cadastro Partner</button></form></div><?php } ?>
<?php if(!empty($novaApiKey)){ ?><div class="alert alert-warning"><strong>Copie esta API key agora. Ela não será exibida novamente.</strong><div class="input-group mt-2"><input id="novaPartnerKey" class="form-control" readonly value="<?= htmlspecialchars($novaApiKey,ENT_QUOTES,'UTF-8') ?>"><div class="input-group-append"><button type="button" class="btn btn-outline-dark" onclick="navigator.clipboard.writeText(document.getElementById('novaPartnerKey').value)">Copiar</button></div></div></div><?php } ?>
<h5>Clientes e números autorizados</h5>
<form method="post" action="<?= BASE_URL ?>/index.php?url=parceiroAdmin/vincular" class="row mb-3"><?= \Core\Csrf::input(); ?><input type="hidden" name="parceiro_id" value="<?= (int)$parceiro['PAR_ID'] ?>">
<div class="form-group col-md-4"><label>Cliente vinculado</label><select name="cliente_id" id="partnerCliente" class="form-control" required><option value="">Selecione</option><?php foreach($clientes as $c){ ?><option value="<?= (int)$c['CLI_ID'] ?>"><?= htmlspecialchars($c['CLI_Nome']) ?> (#<?= (int)$c['CLI_ID'] ?>)</option><?php } ?></select></div>
<div class="form-group col-md-4"><label>Número/conta Meta</label><select name="meta_id" id="partnerMeta" class="form-control" required><option value="">Selecione o cliente</option><?php foreach($contasPorCliente as $cid=>$contas){ foreach($contas as $m){ ?><option class="d-none partner-meta-option" data-cliente="<?= (int)$cid ?>" value="<?= (int)$m['MTA_ID'] ?>"><?= htmlspecialchars($m['MTA_Nome'].' — '.$m['MTA_NumeroTelefone']) ?></option><?php }} ?></select></div>
<div class="form-group col-md-3"><label>ID externo <small>(opcional)</small></label><input name="identificador_externo" class="form-control"></div><div class="form-group col-md-1 d-flex align-items-end"><button class="btn btn-primary">Vincular</button></div></form>
<table class="table table-sm table-bordered"><thead><tr><th>Cliente</th><th>Canal</th><th>ID externo</th><th></th></tr></thead><tbody><?php foreach($canais as $c){ ?><tr><td>#<?= (int)$c['CLI_ID'] ?></td><td><?= htmlspecialchars($c['MTA_Nome'].' — '.$c['MTA_NumeroTelefone']) ?></td><td><?= htmlspecialchars($c['PAC_IdentificadorExterno']??'') ?></td><td><form method="post" action="<?= BASE_URL ?>/index.php?url=parceiroAdmin/desvincular" onsubmit="return confirm('Inativar este vínculo?')"><?= \Core\Csrf::input(); ?><input type="hidden" name="parceiro_id" value="<?= (int)$parceiro['PAR_ID'] ?>"><input type="hidden" name="vinculo_id" value="<?= (int)$c['PAC_ID'] ?>"><button class="btn btn-sm btn-outline-danger">Desvincular</button></form></td></tr><?php } ?></tbody></table>
<hr><h5>API keys</h5><?php if(($parceiro['PAR_StatusCadastro']??'')==='aprovado'){ ?><form method="post" action="<?= BASE_URL ?>/index.php?url=parceiroAdmin/gerarChave" class="form-inline mb-3"><?= \Core\Csrf::input(); ?><input type="hidden" name="parceiro_id" value="<?= (int)$parceiro['PAR_ID'] ?>"><input name="nome" class="form-control mr-2" placeholder="Ex.: Zain produção" required><button class="btn btn-success">Gerar nova API key</button></form><?php }else{ ?><p class="text-muted">A geração de API key será liberada após a aprovação administrativa.</p><?php } ?>
<table class="table table-sm table-bordered"><thead><tr><th>Nome</th><th>Prefixo</th><th>Criada</th><th>Último uso</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($chaves as $k){ $ativa=$k['PAK_Ativo']==='S'&&empty($k['PAK_RevogadaEm']); ?><tr><td><?= htmlspecialchars($k['PAK_Nome']) ?></td><td><code><?= htmlspecialchars($k['PAK_Prefixo']) ?>…</code></td><td><?= htmlspecialchars($k['PAK_CriadoEm']) ?></td><td><?= htmlspecialchars($k['PAK_UltimoUsoEm']??'Nunca') ?></td><td><?= $ativa?'Ativa':'Revogada' ?></td><td><?php if($ativa){ ?><form method="post" action="<?= BASE_URL ?>/index.php?url=parceiroAdmin/revogarChave" onsubmit="return confirm('Revogar esta API key?')"><?= \Core\Csrf::input(); ?><input type="hidden" name="parceiro_id" value="<?= (int)$parceiro['PAR_ID'] ?>"><input type="hidden" name="chave_id" value="<?= (int)$k['PAK_ID'] ?>"><button class="btn btn-sm btn-outline-danger">Revogar</button></form><?php } ?></td></tr><?php } ?></tbody></table>
<hr>
<h4>Financeiro Partner</h4>
<div class="row">
<div class="col-lg-6">
<div class="card bg-light"><div class="card-body">
<h5>Assinatura comercial</h5>
<p class="small text-muted">A implantação é cobrada uma vez. A mensalidade é calculada pelas faixas de clientes faturáveis configuradas abaixo.</p>
<form method="post" action="<?= BASE_URL ?>/index.php?url=parceiroAdmin/salvarAssinaturaFinanceira"><?= \Core\Csrf::input(); ?><input type="hidden" name="parceiro_id" value="<?= (int)$parceiro['PAR_ID'] ?>">
<div class="form-row"><div class="form-group col-md-6"><label>Implantação (R$)</label><input name="valor_implantacao" class="form-control" required value="<?= number_format((float)($assinaturaPartner['PAS_ValorImplantacao']??1490),2,',','') ?>"></div>
<div class="form-group col-md-6"><label>Dia de vencimento</label><input type="number" min="1" max="28" name="dia_vencimento" class="form-control" required value="<?= (int)($assinaturaPartner['PAS_DiaVencimento']??10) ?>"></div></div>
<button class="btn btn-primary">Salvar configuração</button>
</form>
<?php if($assinaturaPartner){ ?><div class="mt-3"><strong>Status:</strong> <?= htmlspecialchars($assinaturaPartner['PAS_Status']) ?> &nbsp; <strong>Clientes faturáveis:</strong> <?= (int)$clientesFaturaveis ?></div>
<form method="post" action="<?= BASE_URL ?>/index.php?url=parceiroAdmin/cobrarImplantacao" class="form-inline mt-3"><?= \Core\Csrf::input(); ?><input type="hidden" name="parceiro_id" value="<?= (int)$parceiro['PAR_ID'] ?>"><label class="mr-2">Vencimento implantação</label><input type="date" name="vencimento" class="form-control mr-2" required value="<?= date('Y-m-d',strtotime('+3 days')) ?>"><button class="btn btn-warning">Gerar / recuperar cobrança</button></form>
<form method="post" action="<?= BASE_URL ?>/index.php?url=parceiroAdmin/cobrarMensalidade" class="form-inline mt-3"><?= \Core\Csrf::input(); ?><input type="hidden" name="parceiro_id" value="<?= (int)$parceiro['PAR_ID'] ?>"><label class="mr-2">Competência</label><input name="competencia" class="form-control mr-2" style="width:100px" required pattern="\d{6}" value="<?= date('Ym') ?>"><label class="mr-2">Vencimento</label><input type="date" name="vencimento" class="form-control mr-2" required value="<?= date('Y-m-d',strtotime('+3 days')) ?>"><button class="btn btn-success">Gerar mensalidade</button></form><?php } ?>
</div></div></div>
<div class="col-lg-6"><div class="card bg-light"><div class="card-body">
<h5>Faixas mensais</h5>
<table class="table table-sm"><thead><tr><th>Faixa</th><th>Clientes</th><th>Valor</th><th></th></tr></thead><tbody><?php foreach($planosPartner as $p){ ?><tr class="<?= $p['PPL_Ativo']==='N'?'text-muted':'' ?>"><td><?= htmlspecialchars($p['PPL_Nome']) ?></td><td><?= (int)$p['PPL_MinClientes'] ?>–<?= $p['PPL_MaxClientes']===null?'∞':(int)$p['PPL_MaxClientes'] ?></td><td>R$ <?= number_format((float)$p['PPL_Valor'],2,',','.') ?></td><td><?php if($p['PPL_Ativo']==='S'){ ?><form method="post" action="<?= BASE_URL ?>/index.php?url=parceiroAdmin/inativarPlanoFinanceiro" onsubmit="return confirm('Inativar esta faixa?')"><?= \Core\Csrf::input(); ?><input type="hidden" name="parceiro_id" value="<?= (int)$parceiro['PAR_ID'] ?>"><input type="hidden" name="plano_id" value="<?= (int)$p['PPL_ID'] ?>"><button class="btn btn-xs btn-outline-danger">Inativar</button></form><?php } ?></td></tr><?php } ?></tbody></table>
<form method="post" action="<?= BASE_URL ?>/index.php?url=parceiroAdmin/salvarPlanoFinanceiro"><?= \Core\Csrf::input(); ?><input type="hidden" name="parceiro_id" value="<?= (int)$parceiro['PAR_ID'] ?>"><div class="form-row"><div class="form-group col-md-4"><input name="nome" class="form-control" placeholder="Ex.: 1 a 5" required></div><div class="form-group col-md-2"><input type="number" min="1" name="min_clientes" class="form-control" placeholder="Mín." required></div><div class="form-group col-md-2"><input type="number" min="1" name="max_clientes" class="form-control" placeholder="Máx."></div><div class="form-group col-md-4"><input name="valor" class="form-control" placeholder="R$ mensal" required></div></div><button class="btn btn-outline-primary btn-sm">Adicionar faixa</button></form>
</div></div></div></div>
<h5>Cobranças Partner</h5>
<table class="table table-sm table-bordered"><thead><tr><th>#</th><th>Tipo</th><th>Valor</th><th>Vencimento</th><th>Status</th><th>Asaas</th><th></th></tr></thead><tbody><?php foreach($cobrancasPartner as $c){ ?><tr><td><?= (int)$c['COB_ID'] ?></td><td><?= htmlspecialchars($c['COB_Tipo']) ?></td><td>R$ <?= number_format((float)$c['COB_Valor'],2,',','.') ?></td><td><?= htmlspecialchars($c['COB_DataVencimento']) ?></td><td><?= htmlspecialchars($c['COB_Status']) ?></td><td><?= htmlspecialchars($c['COB_ProviderStatus']??'') ?></td><td><?php if(!empty($c['COB_LinkPagamento'])){ ?><a class="btn btn-xs btn-outline-primary" target="_blank" rel="noopener" href="<?= htmlspecialchars($c['COB_LinkPagamento'],ENT_QUOTES,'UTF-8') ?>">Abrir cobrança</a><?php } ?></td></tr><?php } ?></tbody></table>
</div></div>
<script>$(function(){$('#partnerCliente').on('change',function(){var id=$(this).val();$('#partnerMeta').val('');$('.partner-meta-option').addClass('d-none').prop('disabled',true);$('.partner-meta-option[data-cliente="'+id+'"]').removeClass('d-none').prop('disabled',false);});});</script>