<div class="card"><div class="card-header"><h3 class="card-title"><?= htmlspecialchars($parceiro['PAR_Nome']) ?> — <?= htmlspecialchars($parceiro['PAR_Identificador']) ?></h3></div><div class="card-body">
<p><strong>Cadastro partner:</strong> <?= htmlspecialchars($parceiro['CLI_Nome']) ?> (#<?= (int)$parceiro['CLI_ID'] ?>)</p>
<p><strong>Status:</strong> <?php if(($parceiro['PAR_StatusCadastro']??'')==='aprovado'){ ?><span class="badge badge-success">Aprovado</span><?php }else{ ?><span class="badge badge-warning">Pendente de aprovação</span><?php } ?></p>
<?php if(($parceiro['PAR_StatusCadastro']??'')!=='aprovado'){ ?><div class="alert alert-warning">Este parceiro ainda não pode receber credenciais da API.<form method="post" action="<?= BASE_URL ?>/index.php?url=parceiroAdmin/aprovar" class="mt-2 mb-0" onsubmit="return confirm('Aprovar este cadastro Partner?')"><?= \Core\Csrf::input(); ?><input type="hidden" name="parceiro_id" value="<?= (int)$parceiro['PAR_ID'] ?>"><button class="btn btn-success btn-sm"><i class="fas fa-check mr-1"></i>Aprovar cadastro Partner</button></form></div><?php } ?>
<?php if(!empty($novaApiKey)){ ?><div class="alert alert-warning"><strong>Copie esta API key agora. Ela não será exibida novamente.</strong><div class="input-group mt-2"><input id="novaPartnerKey" class="form-control" readonly value="<?= htmlspecialchars($novaApiKey,ENT_QUOTES,'UTF-8') ?>"><div class="input-group-append"><button type="button" class="btn btn-outline-dark" onclick="navigator.clipboard.writeText(document.getElementById('novaPartnerKey').value)">Copiar</button></div></div></div><?php } ?>
<h5>Clientes e números autorizados</h5>
<form method="post" action="<?= BASE_URL ?>/index.php?url=parceiroAdmin/vincular" class="row mb-3"><?= \Core\Csrf::input(); ?><input type="hidden" name="parceiro_id" value="<?= (int)$parceiro['PAR_ID'] ?>">
<div class="form-group col-md-4"><label>Cliente vinculado</label><select name="cliente_id" id="partnerCliente" class="form-control" required><option value="">Selecione</option><?php foreach($clientes as $c){ ?><option value="<?= (int)$c['CLI_ID'] ?>"><?= htmlspecialchars($c['CLI_Nome']) ?> (#<?= (int)$c['CLI_ID'] ?>)</option><?php } ?></select></div>
<div class="form-group col-md-4"><label>Número/conta Meta</label><select name="meta_id" id="partnerMeta" class="form-control" required><option value="">Selecione o cliente</option><?php foreach($contasPorCliente as $cid=>$contas){ foreach($contas as $m){ ?><option class="d-none partner-meta-option" data-cliente="<?= (int)$cid ?>" value="<?= (int)$m['MTA_ID'] ?>"><?= htmlspecialchars($m['MTA_Nome'].' — '.$m['MTA_NumeroTelefone']) ?></option><?php }} ?></select></div>
<div class="form-group col-md-3"><label>ID externo <small>(opcional)</small></label><input name="identificador_externo" class="form-control"></div><div class="form-group col-md-1 d-flex align-items-end"><button class="btn btn-primary">Vincular</button></div></form>
<table class="table table-sm table-bordered"><thead><tr><th>Cliente</th><th>Canal</th><th>ID externo</th><th></th></tr></thead><tbody><?php foreach($canais as $c){ ?><tr><td>#<?= (int)$c['CLI_ID'] ?></td><td><?= htmlspecialchars($c['MTA_Nome'].' — '.$c['MTA_NumeroTelefone']) ?></td><td><?= htmlspecialchars($c['PAC_IdentificadorExterno']??'') ?></td><td><form method="post" action="<?= BASE_URL ?>/index.php?url=parceiroAdmin/desvincular" onsubmit="return confirm('Inativar este vínculo?')"><?= \Core\Csrf::input(); ?><input type="hidden" name="parceiro_id" value="<?= (int)$parceiro['PAR_ID'] ?>"><input type="hidden" name="vinculo_id" value="<?= (int)$c['PAC_ID'] ?>"><button class="btn btn-sm btn-outline-danger">Desvincular</button></form></td></tr><?php } ?></tbody></table>
<hr><h5>API keys</h5><?php if(($parceiro['PAR_StatusCadastro']??'')==='aprovado'){ ?><form method="post" action="<?= BASE_URL ?>/index.php?url=parceiroAdmin/gerarChave" class="form-inline mb-3"><?= \Core\Csrf::input(); ?><input type="hidden" name="parceiro_id" value="<?= (int)$parceiro['PAR_ID'] ?>"><input name="nome" class="form-control mr-2" placeholder="Ex.: Zain produção" required><button class="btn btn-success">Gerar nova API key</button></form><?php }else{ ?><p class="text-muted">A geração de API key será liberada após a aprovação administrativa.</p><?php } ?>
<table class="table table-sm table-bordered"><thead><tr><th>Nome</th><th>Prefixo</th><th>Criada</th><th>Último uso</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($chaves as $k){ $ativa=$k['PAK_Ativo']==='S'&&empty($k['PAK_RevogadaEm']); ?><tr><td><?= htmlspecialchars($k['PAK_Nome']) ?></td><td><code><?= htmlspecialchars($k['PAK_Prefixo']) ?>…</code></td><td><?= htmlspecialchars($k['PAK_CriadoEm']) ?></td><td><?= htmlspecialchars($k['PAK_UltimoUsoEm']??'Nunca') ?></td><td><?= $ativa?'Ativa':'Revogada' ?></td><td><?php if($ativa){ ?><form method="post" action="<?= BASE_URL ?>/index.php?url=parceiroAdmin/revogarChave" onsubmit="return confirm('Revogar esta API key?')"><?= \Core\Csrf::input(); ?><input type="hidden" name="parceiro_id" value="<?= (int)$parceiro['PAR_ID'] ?>"><input type="hidden" name="chave_id" value="<?= (int)$k['PAK_ID'] ?>"><button class="btn btn-sm btn-outline-danger">Revogar</button></form><?php } ?></td></tr><?php } ?></tbody></table>
</div></div>
<script>$(function(){$('#partnerCliente').on('change',function(){var id=$(this).val();$('#partnerMeta').val('');$('.partner-meta-option').addClass('d-none').prop('disabled',true);$('.partner-meta-option[data-cliente="'+id+'"]').removeClass('d-none').prop('disabled',false);});});</script>