CREATE TABLE IF NOT EXISTS depoimentos_clientes (
    DEP_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    CLI_ID BIGINT UNSIGNED NOT NULL,
    DEP_NomeExibido VARCHAR(120) NOT NULL,
    DEP_Empresa VARCHAR(160) NOT NULL,
    DEP_Cargo VARCHAR(120) NULL,
    DEP_Depoimento VARCHAR(1000) NOT NULL,
    DEP_Autorizado CHAR(1) NOT NULL DEFAULT 'N',
    DEP_Status ENUM('pendente', 'aprovado', 'rejeitado') NOT NULL DEFAULT 'pendente',
    DEP_EnviadoEm DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DEP_DecididoEm DATETIME NULL,
    DEP_DecididoPor_USU_ID BIGINT UNSIGNED NULL,
    DEP_Ativo CHAR(1) NOT NULL DEFAULT 'S',
    PRIMARY KEY (DEP_ID),
    KEY IDX_DEP_PUBLICACAO (DEP_Status, DEP_Ativo, DEP_Autorizado, DEP_DecididoEm),
    KEY IDX_DEP_CLIENTE (CLI_ID, DEP_EnviadoEm),
    CONSTRAINT FK_DEP_CLIENTE FOREIGN KEY (CLI_ID) REFERENCES clientes (CLI_ID),
    CONSTRAINT FK_DEP_ADMIN FOREIGN KEY (DEP_DecididoPor_USU_ID) REFERENCES usuarios (USU_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
