CREATE TABLE IF NOT EXISTS consumo_estornos_meta (
    CEM_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    CEM_MessageId VARCHAR(255) NOT NULL,
    CLI_ID INT NOT NULL,
    CEM_AnoMes CHAR(6) NOT NULL,
    CEM_Origem VARCHAR(30) NOT NULL,
    CEM_OrigemId INT NOT NULL,
    CEM_CodigoErro VARCHAR(100) NULL,
    CEM_DataCadastro DATETIME NOT NULL,
    PRIMARY KEY (CEM_ID),
    UNIQUE KEY UK_CEM_MessageId (CEM_MessageId),
    KEY IDX_CEM_ClienteMes (CLI_ID, CEM_AnoMes)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
