-- Reservas financeiras internas do Programa de Indicação. Não integra cobrança ou provedor externo.
CREATE TABLE IF NOT EXISTS indicacao_credito_reservas (
    ICRR_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    ICR_ID BIGINT UNSIGNED NOT NULL,
    ICRR_ReferenciaTipo VARCHAR(40) NOT NULL,
    ICRR_ReferenciaID VARCHAR(100) NOT NULL,
    ICRR_Ciclo ENUM('mensal','trimestral','semestral','anual') NOT NULL,
    ICRR_MesesCiclo TINYINT UNSIGNED NOT NULL,
    ICRR_ValorBaseCicloCentavos BIGINT UNSIGNED NOT NULL,
    ICRR_MensalidadeEquivalenteCentavos BIGINT UNSIGNED NOT NULL,
    ICRR_Percentual DECIMAL(5,2) NOT NULL,
    ICRR_DescontoCentavos BIGINT UNSIGNED NOT NULL,
    ICRR_Status ENUM('reservada','utilizada','liberada','cancelada') NOT NULL DEFAULT 'reservada',
    ICRR_ReservadoEm DATETIME NOT NULL,
    ICRR_UtilizadoEm DATETIME NULL,
    ICRR_LiberadoEm DATETIME NULL,
    ICRR_CanceladoEm DATETIME NULL,
    ICRR_CriadoEm DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ICRR_AtualizadoEm DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ICRR_CreditoAtivo BIGINT UNSIGNED GENERATED ALWAYS AS (CASE WHEN ICRR_Status='reservada' THEN ICR_ID ELSE NULL END) STORED,
    PRIMARY KEY (ICRR_ID),
    UNIQUE KEY uk_indicacao_reserva_credito_ativo (ICRR_CreditoAtivo),
    UNIQUE KEY uk_indicacao_reserva_referencia_credito (ICRR_ReferenciaTipo,ICRR_ReferenciaID,ICR_ID),
    KEY idx_indicacao_reserva_referencia (ICRR_ReferenciaTipo,ICRR_ReferenciaID,ICRR_Status,ICRR_ID),
    KEY idx_indicacao_reserva_credito_historico (ICR_ID,ICRR_ID),
    CONSTRAINT chk_indicacao_reserva_meses CHECK (ICRR_MesesCiclo IN (1,3,6,12)),
    CONSTRAINT chk_indicacao_reserva_valores CHECK (ICRR_ValorBaseCicloCentavos>0 AND ICRR_MensalidadeEquivalenteCentavos>0 AND ICRR_DescontoCentavos>=0),
    CONSTRAINT chk_indicacao_reserva_percentual CHECK (ICRR_Percentual>0 AND ICRR_Percentual<=100),
    CONSTRAINT fk_indicacao_reserva_credito FOREIGN KEY (ICR_ID) REFERENCES indicacao_creditos (ICR_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
