<?php

namespace Services\Indicacao;

use Core\Database;
use Models\IndicacaoCredito;
use Models\IndicacaoCreditoReserva;
use PDO;

class IndicacaoDescontoService
{
    private $db;private $creditos;private $reservas;private $reservaService;private $calculo;
    public function __construct(PDO $db=null,IndicacaoCredito $creditos=null,IndicacaoCreditoReserva $reservas=null,IndicacaoCreditoReservaService $reservaService=null,IndicacaoCalculoDescontoService $calculo=null){$this->db=$db?:Database::getInstance();$this->creditos=$creditos?:new IndicacaoCredito($this->db);$this->reservas=$reservas?:new IndicacaoCreditoReserva($this->db);$this->reservaService=$reservaService?:new IndicacaoCreditoReservaService($this->db,$this->reservas);$this->calculo=$calculo?:new IndicacaoCalculoDescontoService();}
    public function prepararDesconto($clienteId,$ciclo,$valorBaseCicloCentavos,$referenciaTipo,$referenciaId):array{$clienteId=(int)$clienteId;$valorBaseCicloCentavos=(int)$valorBaseCicloCentavos;[$referenciaTipo,$referenciaId]=$this->validarReferencia($referenciaTipo,$referenciaId);if($clienteId<=0)throw new \InvalidArgumentException('Cliente inválido.');if($valorBaseCicloCentavos<=0)throw new \InvalidArgumentException('Valor-base deve ser positivo.');$meses=$this->calculo->meses($ciclo);return $this->comLockReferencia($referenciaTipo,$referenciaId,function()use($clienteId,$ciclo,$valorBaseCicloCentavos,$referenciaTipo,$referenciaId,$meses){return $this->transacao(function()use($clienteId,$ciclo,$valorBaseCicloCentavos,$referenciaTipo,$referenciaId,$meses){$existentes=$this->reservas->listarPorReferencia($referenciaTipo,$referenciaId,true);if($existentes)return $this->resultadoDasReservas($existentes);$mensalidades=$this->calculo->distribuirMensalidades($valorBaseCicloCentavos,$meses);$selecionados=$this->creditos->selecionarDisponiveisFifo($clienteId,$meses,true);$itens=[];foreach($selecionados as $indice=>$credito){$mensalidade=$mensalidades[$indice];$desconto=$this->calculo->desconto($mensalidade,$credito['ICR_Percentual']);$dados=['credito_id'=>(int)$credito['ICR_ID'],'referencia_tipo'=>$referenciaTipo,'referencia_id'=>$referenciaId,'ciclo'=>$ciclo,'meses_ciclo'=>$meses,'valor_base_centavos'=>$valorBaseCicloCentavos,'mensalidade_equivalente_centavos'=>$mensalidade,'percentual'=>(string)$credito['ICR_Percentual'],'desconto_centavos'=>$desconto,'reservado_em'=>date('Y-m-d H:i:s')];$dados['reserva_id']=$this->reservaService->criar($dados);$itens[]=$dados;}return $this->montarResultado($referenciaTipo,$referenciaId,$ciclo,$meses,$valorBaseCicloCentavos,$mensalidades,$itens);});});}
    public function confirmarUtilizacao($referenciaTipo,$referenciaId):array{[$referenciaTipo,$referenciaId]=$this->validarReferencia($referenciaTipo,$referenciaId);return $this->comLockReferencia($referenciaTipo,$referenciaId,function()use($referenciaTipo,$referenciaId){return $this->transacao(function()use($referenciaTipo,$referenciaId){$reservas=$this->reservas->listarPorReferencia($referenciaTipo,$referenciaId,true);if(!$reservas)throw new \DomainException('Referência sem reservas.');if($this->todosNoEstado($reservas,'utilizada'))return $this->resultadoDasReservas($reservas);if(!$this->todosNoEstado($reservas,'reservada'))throw new \DomainException('Reservas não podem ser utilizadas no estado atual.');$this->reservaService->utilizar($reservas);return $this->resultadoDasReservas($this->reservas->listarPorReferencia($referenciaTipo,$referenciaId,true));});});}
    public function liberarReservas($referenciaTipo,$referenciaId,$motivo):array{[$referenciaTipo,$referenciaId]=$this->validarReferencia($referenciaTipo,$referenciaId);$motivo=trim((string)$motivo);if($motivo==='')throw new \InvalidArgumentException('Motivo é obrigatório.');return $this->comLockReferencia($referenciaTipo,$referenciaId,function()use($referenciaTipo,$referenciaId,$motivo){return $this->transacao(function()use($referenciaTipo,$referenciaId,$motivo){$reservas=$this->reservas->listarPorReferencia($referenciaTipo,$referenciaId,true);if(!$reservas)throw new \DomainException('Referência sem reservas.');if($this->todosNoEstado($reservas,'liberada'))return $this->resultadoDasReservas($reservas);if(!$this->todosNoEstado($reservas,'reservada'))throw new \DomainException('Reservas não podem ser liberadas no estado atual.');$this->reservaService->liberar($reservas,$motivo);return $this->resultadoDasReservas($this->reservas->listarPorReferencia($referenciaTipo,$referenciaId,true));});});}
    public function garantirReservasDaReferencia($referenciaTipo,$referenciaId,$descontoEsperadoCentavos):array{[$referenciaTipo,$referenciaId]=$this->validarReferencia($referenciaTipo,$referenciaId);$descontoEsperadoCentavos=(int)$descontoEsperadoCentavos;if($descontoEsperadoCentavos<=0)throw new \InvalidArgumentException('Desconto esperado deve ser positivo.');return $this->comLockReferencia($referenciaTipo,$referenciaId,function()use($referenciaTipo,$referenciaId,$descontoEsperadoCentavos){return $this->transacao(function()use($referenciaTipo,$referenciaId,$descontoEsperadoCentavos){$reservas=$this->reservas->listarPorReferencia($referenciaTipo,$referenciaId,true);if(!$reservas)throw new \DomainException('Cobrança com desconto sem reservas históricas.');$total=array_sum(array_map(function($r){return(int)$r['ICRR_DescontoCentavos'];},$reservas));if($total!==$descontoEsperadoCentavos)throw new \DomainException('Reservas incompatíveis com o desconto congelado.');if($this->todosNoEstado($reservas,'reservada'))return $this->resultadoDasReservas($reservas);if(!$this->todosNoEstado($reservas,'liberada'))throw new \DomainException('Reservas não podem ser restabelecidas no estado atual.');$this->reservaService->restabelecer($reservas);return $this->resultadoDasReservas($this->reservas->listarPorReferencia($referenciaTipo,$referenciaId,true));});});}
    private function resultadoDasReservas(array $reservas):array{$p=$reservas[0];$mensalidades=$this->calculo->distribuirMensalidades((int)$p['ICRR_ValorBaseCicloCentavos'],(int)$p['ICRR_MesesCiclo']);$itens=array_map(function($r){return ['reserva_id'=>(int)$r['ICRR_ID'],'credito_id'=>(int)$r['ICR_ID'],'percentual'=>(string)$r['ICRR_Percentual'],'desconto_centavos'=>(int)$r['ICRR_DescontoCentavos'],'mensalidade_equivalente_centavos'=>(int)$r['ICRR_MensalidadeEquivalenteCentavos'],'status'=>$r['ICRR_Status']];},$reservas);return $this->montarResultado($p['ICRR_ReferenciaTipo'],$p['ICRR_ReferenciaID'],$p['ICRR_Ciclo'],(int)$p['ICRR_MesesCiclo'],(int)$p['ICRR_ValorBaseCicloCentavos'],$mensalidades,$itens);}
    private function montarResultado($tipo,$id,$ciclo,$meses,$valorBase,array $mensalidades,array $itens):array{$total=array_sum(array_column($itens,'desconto_centavos'));$reservas=array_map(function($i){return ['reserva_id'=>(int)$i['reserva_id'],'credito_id'=>(int)$i['credito_id'],'percentual'=>(string)$i['percentual'],'mensalidade_equivalente_centavos'=>(int)$i['mensalidade_equivalente_centavos'],'desconto_centavos'=>(int)$i['desconto_centavos']]+(isset($i['status'])?['status'=>$i['status']]:[]);},$itens);return ['referencia'=>['tipo'=>$tipo,'id'=>$id],'ciclo'=>$ciclo,'meses'=>$meses,'valor_base_centavos'=>$valorBase,'mensalidade_equivalente_centavos'=>$mensalidades[0],'distribuicao_mensal_centavos'=>$mensalidades,'quantidade_creditos'=>count($reservas),'desconto_total_centavos'=>$total,'valor_final_centavos'=>$valorBase-$total,'reservas'=>$reservas];}
    private function todosNoEstado(array $reservas,$estado):bool{foreach($reservas as $r)if($r['ICRR_Status']!==$estado)return false;return true;}
    private function validarReferencia($tipo,$id):array{$tipo=trim((string)$tipo);$id=trim((string)$id);if(!preg_match('/^[a-z][a-z0-9_]{1,39}$/',$tipo)||$id===''||strlen($id)>100||!preg_match('/^[A-Za-z0-9:_\-.]+$/',$id))throw new \InvalidArgumentException('Referência inválida.');return[$tipo,$id];}
    private function comLockReferencia($tipo,$id,callable $callback){if(!$this->reservas->adquirirLockReferencia($tipo,$id))throw new \RuntimeException('Não foi possível bloquear a referência.');try{return$callback();}finally{$this->reservas->liberarLockReferencia($tipo,$id);}}
    private function transacao(callable $callback){$p=!$this->db->inTransaction();if($p)$this->db->beginTransaction();try{$r=$callback();if($p)$this->db->commit();return$r;}catch(\Throwable $e){if($p&&$this->db->inTransaction())$this->db->rollBack();throw$e;}}
}
