<!DOCTYPE html><html lang="pt-br"><head>
<?php $googleTagManagerSection = 'head'; require __DIR__.'/../partials/google_tag_manager.php'; ?>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Tarifas do WhatsApp cobradas pela Meta | Disparador.net</title>
<meta name="description" content="Entenda a diferença entre a mensalidade do Disparador.net e as tarifas oficiais cobradas pela Meta pelo uso do WhatsApp Business Platform.">
<link rel="canonical" href="https://disparador.net/precos-whatsapp-meta"><meta property="og:type" content="article"><meta property="og:locale" content="pt_BR"><meta property="og:site_name" content="Disparador.net"><meta property="og:title" content="Tarifas do WhatsApp cobradas pela Meta"><meta property="og:description" content="Mensalidade do Disparador.net e tarifas oficiais da Meta: entenda a diferença."><meta property="og:url" content="https://disparador.net/precos-whatsapp-meta">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"><link rel="stylesheet" href="<?= ASSET_URL; ?>/css/style.css?v=14">
</head><body><?php $googleTagManagerSection = 'body'; require __DIR__.'/../partials/google_tag_manager.php'; ?>
<nav class="navbar navbar-light bg-white shadow-sm"><div class="container"><a class="navbar-brand" href="<?= BASE_URL; ?>/"><img class="site-logo" src="<?= ASSET_URL; ?>/img/logo-disparador.png" alt="Disparador.net" width="1136" height="247"></a><a class="btn btn-outline-success" href="<?= BASE_URL; ?>/index.php?url=site/cadastro">Começar teste grátis</a></div></nav>
<main><header class="py-5 bg-light"><div class="container text-center"><span class="badge badge-success mb-3">Cobrança transparente</span><h1>Tarifas do WhatsApp cobradas pela Meta</h1><p class="lead text-muted mx-auto" style="max-width:800px">O plano cobre o uso do Disparador.net. Separadamente, a Meta cobra pelo uso da WhatsApp Business Platform conforme sua política oficial vigente.</p></div></header>
<section class="py-5"><div class="container"><div class="row"><div class="col-md-6 mb-4"><div class="card h-100"><div class="card-body"><h2 class="h4">Mensalidade do Disparador.net</h2><p class="text-muted">Inclui o uso da plataforma e a franquia prevista no plano contratado. Mensagens excedentes do Disparador seguem as condições exibidas nos planos.</p></div></div></div><div class="col-md-6 mb-4"><div class="card h-100"><div class="card-body"><h2 class="h4">Tarifas oficiais da Meta</h2><p class="text-muted">São separadas da mensalidade e da franquia. Podem variar conforme categoria da mensagem, mercado do destinatário, política vigente e eventuais faixas de volume. O Disparador.net não revende créditos da Meta nem define essas tarifas.</p></div></div></div></div>
<div class="alert alert-light border mt-3"><h2 class="h4">Atualização a partir de 1º de outubro de 2026</h2><p>Até 30 de setembro de 2026, mensagens de Serviço enviadas pela empresa durante a janela de atendimento de 24 horas e templates de Utilidade enviados nessa janela têm tratamento gratuito segundo a política atual aplicável.</p><p>A partir de 1º de outubro de 2026, a Meta anunciou que mensagens de Serviço, incluindo respostas enviadas pela empresa durante essa janela, e templates de Utilidade enviados nela passarão a ser cobrados por mensagem. Mensagens de Marketing e Autenticação continuam sujeitas às respectivas tarifas.</p><p class="mb-0">A alteração é definida pela Meta e não representa aumento da mensalidade do Disparador.net. Exceções e janelas gratuitas continuam sujeitas às regras oficiais vigentes da Meta.</p></div>
<p class="small text-muted mt-4">As políticas e tarifas podem mudar. Consulte as condições oficiais vigentes da Meta no momento do envio.</p><div class="text-center mt-5"><a class="btn btn-success mr-2" data-analytics-event="limites_whatsapp" href="<?= BASE_URL; ?>/limites-whatsapp">Entenda os limites de envio</a><a class="btn btn-outline-success" href="<?= BASE_URL; ?>/">Ver planos do Disparador.net</a></div></div></section></main>
<footer class="py-4 bg-dark text-white text-center">© 2026 RL2 Net — Disparador.net</footer></body></html>
