name: Deploy Hostinger

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: Deploy via FTP
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Tentativa 1 - Enviar arquivos para Hostinger
        id: deploy1
        continue-on-error: true
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftp
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/node_modules/**

      - name: Aguardar antes da nova tentativa
        if: steps.deploy1.outcome == 'failure'
        run: sleep 45

      - name: Tentativa 2 - Enviar arquivos para Hostinger
        id: deploy2
        if: steps.deploy1.outcome == 'failure'
        continue-on-error: true
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftp
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/node_modules/**

      - name: Aguardar antes da terceira tentativa
        if: steps.deploy1.outcome == 'failure' && steps.deploy2.outcome == 'failure'
        run: sleep 90

      - name: Tentativa 3 - Enviar arquivos para Hostinger
        if: steps.deploy1.outcome == 'failure' && steps.deploy2.outcome == 'failure'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftp
          server-dir: ${{ secrets.FTP_SERVER_DIR }}
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/node_modules/**